swaggo/swag

parser.go
parser_test.go

fix: Allow multiple distinct operations for a single path

---

parser.go

Think about :
vendor/xxx.go
xxx/vendor/xxx.go

Fix exclude vendor folder

---

operation.go

// @Summary asd
// @Description asdasdasdasd
// @ID file.upload
// @Accept  multipart/form-data
// @Produce  json
// @Param   file formData file true  "this is a test file"
// @Success 200 {string} string	"ok"
// @Failure 400 {object} s.APIError "We need ID!!"
// @Failure 404 {object} s.APIError "Can not find ID"
// @Router /file/upload [post]
func Upload (ctx *gin.Context) {
// todos 
}
and generate json is :
`
"/file/upload": {
"post": {
"description": "asdasdasdasd",
"consumes": [
"multipart/form-data"
],
"produces": [
"application/json"
],
"summary": "asd",
"operationId": "file.upload",
"parameters": [
{
"type": "file",
"description": "sss",
"name": "file",
"in": "formData",
"required": true
}
],
`

enable  multipart/form-data  and can upload files

---

README.md
operation.go
operation_test.go

feat: add support for tags field

---

operation.go
operation_test.go

This is required for http://jsonapi.org/format/#content-negotiation

Add JSON API Accept/Produces

---

parser.go

See on [https://github.com/swaggo/swag/issues/39](https://github.com/swaggo/swag/issues/39)

quick fix for referencing nested structs

---

parser.go
parser_test.go
schema.go
schema_test.go

cleanup array of structs method and add array of standard types (e.g. []string)
add fix TransToValidSchemeType(typeName string) to support user defined types in ast.Ident fields

add array of standard types

---

parser_test.go
property.go
testdata/simple/web/handler.go

close https://github.com/swaggo/swag/issues/17

feat: add support parsing interface type in swagger schema object (#17)

---

parser.go
testdata/simple/web/handler.go

Add hidden field

---

parser.go
testdata/simple/web/handler.go

Please first merge  https://github.com/swaggo/swag/pull/89
ignore json tag option
```go
type Model struct {
Field int `json:"field,omitempty"`  -> field
}
```

Fix ignore json tag option

---

parser.go

fix (#121)ParseFile panic:.git/logs/refs/heads/main.go

---

cmd/swag/main.go
version.go

Release v1.3 and add `swag.Version` const.

feat: release v.1.3 version

---

parser.go
parser_test.go
testdata/simple/web/handler.go
testdata/simple2/web/handler.go

Support declare a parameter in struct as required [#123](https://github.com/swaggo/swag/issues/123)

feat: support struct field as required.

---

parser.go

#131
close #131
vscode and idea ignore config folder

idea and vscode config folder ignore

---

README.md

delete local document.
**Relation PR**
https://github.com/swaggo/swaggo.io/pull/17

update README document link

---

parser.go
parser_test.go
testdata/struct_comment/api/api.go
testdata/struct_comment/main.go
testdata/struct_comment/web/handler.go

Support parsing struct field descriptions from godoc comments

Add struct field description

---

parser.go
parser_test.go

refactor: exclude hidden folder

---

parser_test.go

add tests for skip method
https://github.com/swaggo/swag/pull/147

test: ensure current path don't skip

---

operation.go
parser.go
swagger.go
version.go

Refine comments

---

operation.go
operation_test.go

feat: support empty response body when only have status code

---

.gitignore
Makefile
property_test.go

for https://github.com/swaggo/swag/issues/164

Add property_test.go and update Makefile

---

parser.go
parser_test.go
property.go
property_test.go
testdata/simple/cross/test.go
testdata/simple/web/handler.go

I also made it possible to create a model in Cross package
close https://github.com/swaggo/swag/issues/159
Very bad code, but it works.

add support cross package

---

property.go

Simple property.go

---

operation.go
operation_test.go
parser.go
parser_test.go
testdata/model_not_under_root/cmd/api/api.go
testdata/model_not_under_root/cmd/main.go
testdata/model_not_under_root/data/foo.go

Finds type definitions that are not under the search directory
https://github.com/swaggo/swag/issues/178
It's not perfect. It doesn't support nested type definitions from outside the search dir.

Support type definitions not found under the search directory

---

parser.go
parser_test.go

This is for trimming new lines from struct field descriptions
https://github.com/swaggo/swag/issues/186

#186: remove new line from struct field description

---

README.md

Revise the `README.md` to correct the description of `@router`

[docs]Revise the description of `@router`

---

.travis.yml

Add `go1.11` testing at Travis CI.

 test: add go1.11 testing

---

README.md

Add content section and adjust section order.

doc: add content section and adjust section order

---

README.md

Minor fix to gin link in README
N/A
Test: https://github.com/jones77/swag/blob/master/README.md#how-to-use-it-with-gin

Update gin link in README.md

---

schema.go

Added comment to schema.go about CheckSchemaType function
Absent
Absent

Added comment to schema.go

---

README.md

https://github.com/swaggo/swag/pull/331#issuecomment-475111610

update README for parseVendor in cli section

---

.github/ISSUE_TEMPLATE/Bug_report.md

I want to know use `go` which version because user have issue from `go` version or `swag` version or another.

update issue template for bug report

---

parser.go

refactor: return error instead of panic

---

operation.go

refactor parseAndExtractionParamAttribute.

refactor parseAndExtractionParamAttribute

---

operation.go

use trim spaced string

---

README.md
parser.go
parser_test.go
testdata/struct_comment/web/handler.go

support line-comments to struct comment
Comments written on top of the field are not beautiful

support line-comments to struct comment

---

README.md

fix: fixed link into readme

---

README.md

chore(doc): fix cli desc

---

.github/ISSUE_TEMPLATE/Bug_report.md

bug_report.md file was fixed to one standard
None
None

fix: repair bug_report.md to one standard

---

README.md

Add Go version at go get paragragh 

Add Go version at go get paragragh

---

README.md

Looking at it is a bit confusing。Is that so?

doc(readme): fix Param Type option desc

---

debug.go
property.go

fix(property): remove warning

---

README.md

chore(readme): add release badge

---

parser.go
parser_test.go
testdata/deps_having_invalid_pkg/main.go

fix: ignore .go files in 'testdata' folder because it can be invalid 

---

parser.go
parser_test.go
testdata/struct_comment/web/handler.go

enhancement: remove backticks from struct field's comment
Issue #381 
None.

enhancement: remove backticks from struct field's comment

---

example/basic/api/api.go

fix: variables in the assignment caused compile error

---

README.md

Readme update - tag.docs.description typos
NA
NA

tag.docs.description typos

---

parser.go
parser_test.go
testdata/simple/web/handler.go

support for read only.
https://github.com/swaggo/swag/issues/524

support for read only

---

version.go

https://github.com/swaggo/swag/issues/522

chore: jump version to v1.6.3

---

operation.go
operation_test.go
parser_test.go

Improve swagger schema validity.
Fix #525
None.

Fix issue 525

---

parser_test.go

Enable the tests back after fixing github action.
None.
As was convinced the files where committed in the last PR.

Re-enable tests

---

operation.go
operation_test.go

fix bug in array param in body

---

.github/workflows/ci.yml

Fix GitHub action.
None
I hope to be the last addressed PR for this issue.

Working directory issue.

---

operation.go
operation_test.go

Fixed [Issue 592](https://github.com/swaggo/swag/issues/592)

Fixed issues_592: Use of go primitive array type in body give error

---

README.md

Fixed typo and rephrased this.

Fix typo on README page

---

version.go

chore: jump to v1.6.5

---

.travis.yml

chore(travis): add go 1.14 test

---

example/celler/controller/accounts.go

Fix few documentation typos.
Not a big deal, but I'm sure I'm not the only one seeing them 😊 
+ I believe this could introduce errors when people copy/paste the example.
Thanks for the awesome package!

Examples: Fix doc typos in accounts.

---

README.md
README_zh-CN.md

Add Chinese translation of readme.
https://github.com/swaggo/swag/issues/695
None

Add Chinese translation of readme #695

---

operation.go
operation_test.go

Override deep-level fields in request body object
https://github.com/swaggo/swag/issues/649

Override deep-level fields in request body object

---

cmd/swag/main.go

fix: short aliase flag is not working

---

parser.go

Fix [ci build failed](https://github.com/swaggo/swag/runs/784669622) because of fmt-check lint.

fix: fmt check lint

---

README_zh-CN.md

fix README_zh-CN typo

---

parser.go
testdata/composition/api/api.go

**Related issue:** close https://github.com/swaggo/swag/issues/751

Don't generate docs for nested structs without fields

---

README.md

Add readme to new parseDepth flag

parseDepth flag readme

---

version.go

fix wrong version showed

---

version.go

Will release V1.7.0 after merged the PR.

chore: release v1.7.0

---

cmd/swag/main.go
gen/gen.go
parser.go

:wave: - I would like to have controllers split over multiple files, so this adds support for multiple search dirs. thanks to @sdghchj for the initial implementation in #727 
retarget of 0eb65a69a1f603e43383f78842c01a0adf9d217b without large scale refactoring
#682
n/a

support searching multiple directories

---

README_zh-CN.md

Fix security link in readme.md Chinese version.
#956
None

fix security link

---

testdata/quotes/expected.json

Fix for wrong exptected.json on #743 
#743 
None.

fix expected.json

---

operation.go
parser.go

This helps debugging of the problems and improves the usability of swag. As other error messages prints the
problematic value, this seems like the easiest change.
https://github.com/swaggo/swag/issues/920

provide example and enum values when reporting unsupported type

---

version.go

release v1.7.1

---

operation.go
operation_test.go
parser.go
parser_test.go
schema_test.go

improve code coverage
enable parallel tests 
NONE
NONE

improve unit tests

---

parser.go
parser_test.go
schema.go
testdata/simple/expected.json

Handling of interface objects to any type. 
rewrite of outdated open PR #884 
#850
NONE

Handle *ast.InterfaceType as any type (no type)

---

README.md
README_zh-CN.md

update install doc for go 1.17

update install doc for go 1.17

---

version.go

release v1.7.3

---

README_zh-CN.md

Fix link in Chinese introduction

Fix link in Chinese introduction

---

parser.go
parser_test.go

add test for @X-tagGroups
#916 
NONE

fix @x-tagGroups

---

README.md
README_zh-CN.md
operation.go
parser.go
parser_test.go

add root level @Accept @Produce to help on reducing boilerplate.
#887 
None.

root level accept/produce params

---

README.md

fix: typo error

---

version.go

chore: increment version

---

README.md

fixing the documentation hyperlink

fix: documentation fix formatter link

---

field_parser.go
field_parser_test.go

add separate tag for x-enum-varnames that supports arrays
[https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1081)

Add separate x-enum-varnames tag

---

operation.go
operation_test.go
testdata/quotes/api/api.go
testdata/quotes/expected.json

fix assignment to entry in nil map with @Header all 
#1082 
NONE

fix: assignment to entry in nil map with @Header all #1082

---

version.go

chore: release 1.7.7

---

version.go

release v1.7.9

---

version.go

release a next version (1.8.0)
NONE
NONE

chore: update version.go

---

README_zh-CN.md

Chinese README has some broken links, and this PR fixes them.

fix(README_zh-CD.md): broken link

---

README_zh-CN.md

fix  a Chinese translate bug
no
no

fix: README_zh-CN.md translate bug

---

version.go

chore: increment version to 1.8.3

---

generics_test.go

Cleanup generics_test.go
#1225
None

chore: cleanup generics_test.go

---

version.go

Increment version for version 1.8.4
None
None

chore: increment version release 1.8.4

---

version.go

chore: update version

---

.github/workflows/ci.yml
README.md
README_zh-CN.md

drop support for go 1.15
None
None

chore: drop go 1.15 support

---

README.md
README_zh-CN.md

add Hertz to supported web frameworks
https://github.com/swaggo/swag/issues/1359

docs: add Hertz to supported web frameworks

---

version.go

chore: increment version.go

---

.github/workflows/docker.yml
version.go

Doing an RC for fun
None.
None.

chore: release candidate

---

.github/workflows/docker.yml

revert docker login action
None
None

revert docker login-action

---

version.go

release 1.8.9

---

.goreleaser.yml

enable release build for darwin/arm64
#1445
None

enable build support for macOS arm64

---

.goreleaser.yml

update deprecated options in goreleaser.yml for 1.4.x compatibility
None
None

chore: update deprecated goreleaser.yml

---

README.md
cmd/swag/main.go
gen/gen.go
parser.go
parser_test.go

Add collection format flag
ex) `swag init --collectionFormat multi` or `swag init --cf multi`

feat: ADD collection format flag

---

operation.go
parser.go
schema.go
testdata/enums/api/api.go
testdata/enums/expected.json

fix: field of enum type as formdata
#1510

fix field of enum type as formdata

---

.github/workflows/ci.yml

chore: add v2 to ci

---

field_parser.go
field_parserv3.go
operation.go
operationv3.go
parserv3.go
testdata/parseExtension/parseExtension.go

chore: linting code

---

README.md
README_pt.md

Add Portuguese language option in default readme

Add option language Portuguese in readme

---

gen/gen.go
go.mod
go.sum

chore: replace github.com/ghodss/yaml with sigs.k8s.io/yaml (#1520)

---

README_zh-CN.md

remove repeat net/http
None
Sync

Update README_zh-CN.md (#1545)

---

field_parser.go
field_parser_test.go
field_parser_v3_test.go
field_parserv3.go
operation.go

Based on #1385 I implemented the pattern tag

V2: Implement pattern tag

---

parser.go

Hi! Hope you could consider this change :)
Add some more tracability to the errors generated by the parser. This can change this message:
```
**2023/01/09 17:33:42 ParseComment error in file /home/user/bla/bla/file.go :need array item type after array**
```
To a more descriptive:
```
**2023/01/09 17:33:42 ParseComment error in file /home/user/bla/bla/file.go :view.Events: Event: featureRequest: LocalizedItems: LocalizedItem: itemIds: need array item type after array
```
None
What this solves is that with the first message we don't know where to look, but with the second message it explains which field the error ocured for as it might be far far away from the starting. The example above is the actual depth the parser was at, so …

Enchancement: Report which property is triggering a parsing error

---

format/format.go

Fix #1631 with a byte check to skip rewriting files that has no change.
#1631

Skip rewriting files that have no changes

---

version.go

security update for gopkg.in/yaml.v3
#1663

yaml.v3 security patch

---

packages.go

If a type is an alias type from a dependent package and they share the same short package name and type name, the dependent type will be hidden. So this PR will search for type definitions from dependent packages first.
#1662

fix: search for definitions from dependent packages first

---

parser.go
parser_test.go

Added multiline support for @description attribute for securityDefinitions
<none>
<none>

Added multiline support for @description attribute for securityDefinitions

---

README.md

Update the README for the English version.
* Updated the descriptions of the functionalities supported by the CLI and the installation instructions.
n/a
- Only update the documentation to help users easily use version 2.

docs: Updated the descriptions of the functionalities supported by the CLI and the installation instructions for v2

---

version.go

new release
