swaggo/swag

operation.go
Adding the custom header in Param
=> Adding custom header

example/simple/web/handler.go, parser.go, parser_test.go
Please merage #61 
OK
```console
2018/03/05 15:19:18 map[example/simple/api/api.go:0xc420476d00 example/simple/docs/docs.go:0xc420476e80 example/simple/main.go:0xc420477000 example/simple/web/handler.go:0xc420477280]
```
NG
```console
2018/03/05 15:19:16 map[example/simple/api/api.go:0xc420469d80 example/simple/main.go:0xc420469f00 example/simple/web/handler.go:0xc420442180]
--- FAIL: TestGetAllGoFileInfo (0.00s)
assertions.go:238: 
Error Trace:	parser_test.go:67
Error:      	Not equal: 
expected: 4
actual  : 3
Test:       	TestGetAllGoFileInfo
```
There was a difference of docs.go which made to ignore.
Because it fails depending on execution timing, I put static file is prepared.
=> fix: build failed at 1.10.x version(#63)

parser.go, parser_test.go, testdata/simple/web/handler.go
=> Fix infinite loop generated from repeating structure

parser.go
I pulled out the common statement `strings.Split(comment.Text(), "\n")` in parser.go.
=> update: pull out common splitting comment

parser_test.go, property.go, testdata/simple/web/handler.go
for https://github.com/swaggo/swag/issues/112
=> Add support Decimal and ptr slice

operation.go, operation_test.go
=> add octet-stream mimetype

operation.go, operation_test.go
add mime type for comsumes and aproduces
- image/png
- image/jpeg
- image/gif
https://github.com/swaggo/swag/issues/135
=> add image mimetypes

property.go
This reverts commit 657cedde2f1bfac42ea44b147538bfdaf9503860.
```console
panic: Account is not basic types
goroutine 1 [running]:
github.com/swaggo/swag.CheckSchemaType(0xc420460a77, 0x7)
/Users/jumpei/go/src/github.com/swaggo/swag/schema.go:11 +0x241
github.com/swaggo/swag.(*Parser).parseField(0xc42008d470, 0xc4200942c0, 0xc420118fc0)
/Users/jumpei/go/src/github.com/swaggo/swag/parser.go:527 +0x85
github.com/swaggo/swag.(*Parser).parseStruct(0xc42008d470, 0xc4203f35d9, 0x5, 0xc4200942c0, 0xc420320600)
/Users/jumpei/go/src/github.com/swaggo/swag/parser.go:439 +0x77
github.com/swaggo/swag.(*Parser).parseTypeSpec(0xc42008d470, 0xc4203f35d9, 0x5, 0xc420369680, 0xc420320570)
/Users/jumpei/go/src/github.com/swaggo/swag/parser.go:411 +0x24d …
```
=> Revert "refactor: refactoring property.go more simple (#130)"

parser.go
Fix skip all directory.
none
`searchDir` arguments of `getAllGoFileInfo` Function is './' .
Skip following directory, because this code.
```
if f.IsDir() && len(f.Name()) > 0 && f.Name()[0] == '.' {
return filepath.SkipDir
}
```
=> fix: exclude all directory

operation.go, parser_test.go, schema.go, testdata/simple/api/api.go
fix invalid response type: array of strings
close  https://github.com/swaggo/swag/issues/172
=> fix invalid response type: array of strings

property.go
Missing validation of the type assertion on arrays
Fixed property type assertion verification resulted in a false positive ok which came from the top validation.
none
Before this fix I was getting this panic exit, because the assertion was wrongly positive.
```
panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident
goroutine 1 [running]:
github.com/swaggo/swag.getPropertyName(0xc42044dc80, 0xc4204bce40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/Users/ricardomalta/go/src/github.com/swaggo/swag/property.go:99 +0x12be
github.com/swaggo/swag.(*Parser).parseField(0xc4204bce40, 0xc42044dc80, 0xc420983ea0)
/Users/ricardomalta/go/src/github.com/swaggo/swag/parser.go:583 +0x4d …
```
=> Fixed missing type assertion verification

operation.go, operation_test.go
If the pkg referenced in `importPath` is actually a package that is vendored, use the "full path" for the `program.Package(..)` call. Calling on `program.Package(originalmportPath)` will cause the return pkg to be nil, even though the `.Load(..)` succeeded.
#188 
I added some extra new lines during debugging - sorry! Looking at it now, I suppose the map iteration can happen after initial `program.Package(..)` call fails.. but that may be a overkill.
=> minor fix to address referencing types in external, vendored pkgs #188

parser.go, parser_test.go, property.go, property_test.go, schema.go, testdata/simple2/web/handler.go
Handle custom primitive types
https://github.com/swaggo/swag/issues/164
=> Custom primitive types

gen/gen.go, parser.go, parser_test.go
Enhance error handle, there are a lot of  snippets should  returns error instead of panic.
=> refactor: enhance error handle

parser.go
sorry wasn't able to implement the method. This just removes the panic from parseTypeSpec.
https://github.com/swaggo/swag/issues/207
=> remove panic in favor of printed warning

operation.go, operation_test.go
Added support for the `+` sign in Router path param. 
Didn't raise an issue, but asked on StackOverflow if there was a way of doing this prior to the PR
https://stackoverflow.com/questions/52515452/how-to-set-escape-proxy-as-a-path-with-gin-and-swagger
I wanted to generate swagger containing the plus sign, like so:
```
"/exampleapp/proxy/{proxy+}": {
"get": {
"produces": [
"application/json"
],
"summary": "GET proxied request"
}
}
```
However, due to the regex the RouterParser uses, it was being dropped, so I ended up with:
```
"/exampleapp/proxy/{proxy": {
"get": {
"produces": [
"application/json"
],
"summary": "GET proxied request"
}
}
```
AWS API  Gateway parses swagger files, and in order to enable proxying of requests you …
=> Router path now supports plus sign

parser_test.go, property.go, testdata/simple/web/handler.go
First of all, thank you very much for the wonderful project :+1: 
Now to the issue. Previously, the following structure:
type Foo struct {
Bar []int
}
would generate this swagger spec:
...
Bar:
items:
type: int
...
`int`, however, is not a valid swagger type. It is inserted because array types are not processed by the translation function. This commit applies the type translation function to all the places where array types are used.
=> Translate array type into a valid swagger type

parser.go, parser_test.go, testdata/simple/web/handler.go
This PR adds support for examples for numeric array fields. It depends on #232.
=> Support examples for numeric array fields

README.md, parser.go, parser_test.go, schema.go, testdata/simple/web/handler.go
This commit adds support for the following attributes in the struct fields:
- `minimum`, for numeric fields, via `minimum:"value"` struct tag
- `maximum`, for numeric fields, via `maximum:"value"` struct tag
- `minLength`, for string fields, via `minLength:"value"` struct tag
- `maxLength`, for string fields, via `maxLength:"value"` struct tag
- `enums`, via `enums:"value1,value2,value3"` struct tag
- `default`, via `default:"value"` struct tag
All these tags except `default` are also supported in array fields.
=> Add support for the attributes in struct fields

parser.go, parser_test.go, testdata/simple/api/api.go, testdata/simple/web/handler.go
Currently, the function does not use its `refTypeName` parameter; instead it checks that the 1st structure in the structures stack does not repeat. Recursion, however, can be indirect. Consider the
following example:
type Foo struct {
Bar Bar
}
type Bar struct {
Foo Foo
}
type Baz struct {
Foo Foo
}
In the example generator will crash with stack overflow while trying to generate spec for `Baz` when there is no spec for `Foo` and `Bar` generated yet.
The fix is to check that `refTypeName` does not repeat in the structures stack.
=> Fix isNotRecurringNestStruct function

property.go, property_test.go
Add support for map and struct pointer types. 
Add support for selector expression in array pointer type 
Should address #221.
=> Add support for map and struct pointer types and selector in array pointer

parser.go, parser_test.go, property.go, testdata/simple/api/api.go, testdata/simple/web/handler.go
Add support for several kinds of type definitions. Specifically:
- `type Foo Bar`
- `type Foo *Bar`
- `type Foo []Bar`
- `type Foo []struct{...}`
- `type Foo pkg.Bar`
One caveat regarding `type Foo []Bar` definition: instead of referencing `Bar` schema in items' type, it copies it over because from the point of `parseTypeExpr` function call it is impossible to reliably detect
whether the type of array items is a named struct or anonymous one.
=> Support additional typedefs

.gitignore
.gitignore was ignoring a file from the project `cmd/swag/main.go`
=> Prevent cmd/swag/main.go from being ignored

parser.go, parser_test.go, testdata/simple/api/api.go, testdata/simple/web/handler.go
this fixes a bug introduced in https://github.com/swaggo/swag/commit/a2ee966466be717ea86abf7e3d0cd1fe23b6fa46
The `required` for the `name` property was being dropped for anonymous fields (see `web.Pet5` that I added to the test case).
=> fix bug for required properties inherited from anonymous field.

README.md
Add a link to [buffalo-swagger](https://github.com/swaggo/buffalo-swagger) in the README
Fixes #214
=> Add link to buffalo-swagger

README.md
Fix README.md example when referencing docs.Title and docs.Description
=> Fix docs. Title, Description reference in README.md

parser.go, parser_test.go, testdata/simple/api/api.go, testdata/simple/web/handler.go
there's 2 parts in this PR, first off `ParseDefinitions` will now always do the same order (alphabetically), this is to make sure that if there's a bug that it will always pop up and not randomly based on the order of the map.  
So this doesn't actually fix anything, it just makes sure that there's consistency, otherwise tests sometimes fail and sometimes pass...
the second part is the actual bug fix, if a struct (`web.Pet5b`) was parsed before another struct that was using that struct as anonymous field (`web.Pet5a` and `web.Pet5c`) then we would aggregate the `required` from all the properties on `web.Pet5b` and store it on the `spec.Schema` of `web.Pet5b`.  
then when doing `parseAnonymousField` we wouldn't actually see the `required` anymore of the fields, because they were aggregated …
=> Anon struct order bugfix

parser.go, parser_test.go
show the file name when ParseRouterAPIInfo panic
no issue
When I use this tool. My project has many file in one package. 
So add File name in panic can hep use to found where has wrong more quickly
=> add filename info when panic

README.md
It seems `format` was already implemented: https://github.com/swaggo/swag/pull/102
I also tried to use it with `format: "date-time"` and it seems to work
=> Update README: future is available

parser.go, parser_test.go, testdata/simple/api/api.go
e.g. add cool parser.
if map value is string,it will crash!
```go
type SwagReturn []map[string]string
// @Success 200 {object}  main.SwagReturn	"ok"
func test(){}
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13f0b28]
goroutine 1 [running]:
github.com/swaggo/swag.(*Parser).ParseDefinition(0xc000334140, 0xc00002e95a, 0xa, 0xc000454676, 0x6, 0x0)
/Users/windpro/code/github/swag/parser.go:447 +0x218
github.com/swaggo/swag.(*Parser).parseTypeExpr(0xc000334140, 0xc00002e95a, 0xa, 0x0, 0x0, 0x1596240, 0xc0002f4260, 0x0, 0x0, 0x0, ...)
/Users/windpro/code/github/swag/parser.go:545 +0x27f …
=> fix bug: []map[string]string type will crash!

README.md, operation.go, operation_test.go
New features. Parse header comment and add to response.
Add a comment with header in the same format as the success tag.
`// @Header 200 {string} Location "entity/10"`
It is possible to add multiple headers to the same response code.
Header comment must be defined after success tag.
Example:
```
// @Success 200 {string} string	"hello"
// @Header 200 {string} Location "/entity/1"
// @Header 200 {string} Token "qwerty"
```
will generate
```
responses:
"200":
description: hello
headers:
Location:
description: /entity/1
type: string
Token:
description: qwerty
type: string
schema:
type: string
```
=> Add response headers

README.md, operation.go, operation_test.go
This fixues issue #303.
Fixes the issue that `swag` currently rejects most valid MIME Types because the MIME Types accepted by `swag` are a hard-coded list in the code.
The patch keeps the mapping for alias like `json` ⇒ `application/json` or `xml` ⇒ `text/xml` alive, which means regarding aliases, the behavior remains the same. The code is just simplified, replacing the `switch case` chain with a `map`. This makes it easier to add more aliases in future, and also makes it possible in future to create user-definable alias maps.
The patch also removes the redundancy between `ParseAcceptComment` and `ParseProduceComment` by extracting the duplicated code into a common new function `parseMimeTypeList`.
The core of the patch is to have a `mimeTypePattern` in place, which …
=> Fix #303 swag rejects valid MIME Types for Produce annotation, panic

operation.go
Fix a minor spelling error "suppoted" -> "supported" in ParseComment.
=> Fix spelling error in ParseComment

README.md, cmd/swag/main.go, gen/gen.go, gen/gen_test.go
=> feat: add output flag to specify output dir

cmd/swag/main.go, gen/gen.go, operation.go, parser.go, parser_test.go
Support parse definition in vendor, for issues/242
https://github.com/swaggo/swag/issues/242
https://github.com/swaggo/swag/issues/242
I found that this tool can work well, expect for parsing this file: https://github.com/swaggo/swag/blob/master/operation.go
Which file is in this repo~~ So I ignored this repo when parse vendor folder
=> Support parse definition in vendor, for issues/242

Makefile
https://stackoverflow.com/questions/448910/what-is-the-difference-between-the-gnu-makefile-variable-assignments-a
I want to use better Immediate set than lazy val.
=> use Immediate set in Makefile

.golint_exclude, Makefile, example/basic/api/api.go, example/basic/web/handler.go, example/celler/controller/controller.go, example/celler/httputil/error.go, example/celler/model/account.go, example/celler/model/admin.go, example/celler/model/bottle.go, example/celler/model/error.go
=> fix go lint error

parser.go, property.go, property_test.go
=> refactor for property.go

parser.go
Having exists duplicate code snippets, will refactor better with other new PR.
ref #348
=> refactor(parser): using error instead of panic

README.md
as title, and and issue link let users can quickly searchable.
=> chore(readme): make swaggertype examples more readable

operation.go, parser.go, parser_test.go, property.go, property_test.go, schema.go, schema_test.go
fix https://github.com/swaggo/swag/issues/348
=> refactor: return error instead of panic

example/celler/controller/accounts.go
I found typos in the example app.
- compleate -> complete
- finename -> filename
=> fix(example): fix typos in UploadAccountImage message

parser_test.go, property.go, testdata/alias_type/api/api.go, testdata/alias_type/data/alias.go, testdata/alias_type/main.go, testdata/alias_type/types/alias.go
Add ability to use alias types from another package.
https://github.com/swaggo/swag/issues/402
=> Fix processing alias type in struct when alias type is in another package

operation.go, operation_test.go
Added operation parser for @Deprecated method
#404
=> Added deprecation parsing

README.md, cmd/swag/main.go, gen/gen.go, parser.go
add option to explicitly include or exclude third party dependencies
#425
=> add option to explicitly include or exclude third party dependencies

parser.go, parser_test.go, testdata/fixes-432/a/a.go, testdata/fixes-432/b/b.go, testdata/fixes-432/cmd/main.go
=> fix: fail when searchDir contains no package

README.md, gen/gen.go
Ability to set "schemes" programatically
PR for ISSUE: #433
=> feat: ability to set "schemes" programatically

example/basic/api/api.go, parser.go, parser_test.go, testdata/pare_outside_dependencies/cmd/main.go
=> fix: only execute 'go list' when enable 'parseDependency' flag

parser.go, parser_test.go
Nested Struct (Promoted fields) aren't showing properly in the documentation. 
#376
None.
=> feat: embeded struct not parsed

.gitignore, parser.go, parser_test.go
fix issue 474
fix issue 461
repair case tests
#474 
#461 
=> fix: error resolving host and basepath

gen/gen.go
Fixed an issue where the JSON breaks when programmatically setting a Multiline API Description.
#480
=> Fixed JSON issue with Multiline API Description

Makefile, gen/gen_test.go
Add code coverage for generated docs.go
None
There is 0% coverage for any of the docs.go generated files.
=> docs.go test coverage

operation.go, parser.go
code-refactoring
```
$ ~/go/bin/gocyclo -over 15 .
48 swag (*Parser).parseField parser.go:1010:1
46 swag (*Parser).ParseGeneralAPIInfo parser.go:177:1
33 swag (*Parser).parseStructField parser.go:764:1
16 swag (*Operation).parseAndExtractionParamAttribute operation.go:233:1
```
None
Original [results](https://goreportcard.com/report/github.com/swaggo/swag)
```
Gocyclo calculates cyclomatic complexities of functions in Go source code. The cyclomatic complexity of a function is calculated according to the following rules: 1 is the base complexity of a function +1 for each 'if', 'for', 'case', '&&' or '||' Go Report Card warns on functions with cyclomatic complexity > 15.
swag/parser.go
Line 177: warning: cyclomatic complexity 83 …
```
=> Reduce code complexity

go.mod, go.sum
https://github.com/swaggo/swag/pull/491#issuecomment-519574199
go mod can't multi go.mod.
https://github.com/swaggo/swag/pull/491#issuecomment-519753504
I decided to delete it once.
Please let me know if there are other ways.
=> delete deps for example.

.travis.yml, Makefile
swag is't need `go lint` for go modules.
=> exclude developer tools from go modules.

README.md
Add example usage for swaggertype. 
#379 
None
=> Additional Example for swaggertype

operation.go, operation_test.go, parser.go, parser_test.go, testdata/nested/api/api.go, testdata/nested/common/data.go, testdata/nested/expected.json, testdata/nested/main.go, testdata/nested2/data.go
When I use swag, I found two problems;
1. Nested structs inside can not be parsed correctly.
2. When the response struct and the API function exist in the same file, the struct can not be parsed.
https://github.com/swaggo/swag/issues/504
=> Fix nested struct parsing

.gitignore, operation.go
This PR corrects the error in checking for primitive data type.
Bug introduces in https://github.com/swaggo/swag/commit/d74ed70e44450ffd5ca0016f0e78e2c569abbc45.
I am seeing this error in the latest build:
```
$ swag init -g cmd/cnc.go
2019/09/11 11:35:02 Generate swagger docs....
2019/09/11 11:35:02 Generate general API Info, search dir:./
2019/09/11 11:35:02 ParseComment error in file cmd/cnc.go :can not find schema type: "cmd.int"
```
=> Correct error in checking for primitive data type

README.md, cmd/swag/main.go, gen/gen.go
Fix typos in both README and `-h` command
=> fix(readme): fix typos

operation.go, operation_test.go
Useful for custom methods using custom verbs
Add colon sign support for router parse method.
https://github.com/swaggo/swag/issues/551
Custom methods as described in the Google API design documentation (https://cloud.google.com/apis/design/custom_methods) does not work ATM. ex:
/objects:move [post]
Unit test are passing. Fix works well on my side.
Do you want me to change the commit type from "fix" to "feat"?
Is the unit test enough?
Have a good day!
=> fix: router now support colon sign

parser.go, parser_test.go, property.go, testdata/alias_import/api/api.go, testdata/alias_import/data/applicationresponse.go, testdata/alias_import/expected.json, testdata/alias_import/main.go, testdata/alias_import/types/application.go
Add the ability to parse refs with import aliases.
https://github.com/swaggo/swag/issues/483
=> fix issue with import aliases (#483)

README.md, parser.go, parser_test.go, testdata/composition/expected.json
1. optimization: parseTypeExpr return poionter to spec.Schema.
2. optimization: struct parsed as definition ref, which may decrease output size.
3. fully support map type, including map[string]interface{},map[string]primitive, also fix bug described in #581.
=> fully support map and optimization

parser.go, parser_test.go, property.go
=> support []map

parser.go, parser_test.go, property.go
optimize getArrayPropertyName; 
support [][]string fixing bug mentioned by #562, also #510
=> optimize getArrayPropertyName; support [][]string fixing #562

parser.go
Change the condition for checking custom arrayType, only if arrayType is specified by flag `swaggertype` 
fix #558
=> change the condition for checking custom arrayType

operation.go, operation_test.go, parser_test.go, schema.go
Extend struct's simple members in query param, that is, allow struct type in query param comment.
**Relation issue** 
#518
=> feature: extend struct's simple members in query comment

README.md
Fix a link anchor `#dataTypeFormat` which refers nowhere. 
Now it refers to OpenAPI Spec v2, to `Data Types` table.
=> Fix dataTypeFormatlink link.

cmd/swag/main.go, go.mod, go.sum
`go get -u github.com/swaggo/swag/cmd/swag` results in some errors because the `https://github.com/urfave/cli` implementation changed.
Snippet of the error message:
```
../github.com/swaggo/swag/cmd/swag/main.go:25:16: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../github.com/swaggo/swag/cmd/swag/main.go:30:16: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../github.com/swaggo/swag/cmd/swag/main.go:35:16: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal: …
```
=> feat:  migrate to using`/urfave/cli/v2` 

parser.go, property.go, property_test.go
If code uses two packages that contains types with same name, swag generate wrong json/yaml. This PR fixes this.
Fixes #225 
This changes need testing on bigger swag files.
=> Conflicting package + struct name

README.md, operation.go, parser.go, parser_test.go, property.go, schema.go
Rename model to display in swagger UI.
#628 #316
=> feat: support renaming model to display in swagger UI

README.md, parser.go
Add tag 'swaggerignore' to exclude a field from struct
#632
=> Add tag 'swaggerignore' to exclude a field from struct

README.md, cmd/swag/main.go, gen/gen.go, operation.go, operation_test.go, parser.go, schema.go
feature: support collectionFormat for array params in query.
feature: use  flag -exclude to exclude directories and files when searching APIs.
Fix bug: can't find dependent packages when running on windows and both --dir and --parseDependency are set.
#636 #640
=> Support colletionFormat for array params in query; Exclude directories and files

README.md, operation.go, operation_test.go
Add support for inheritance/Model Composition in Response with allOf and ref.
syntax:
```go
// @success 200 {object} jsonresult.JSONResult{data=proto.Order} "desc"
// @success 200 {object} jsonresult.JSONResult{data=[]proto.Order} "desc"
// @success 200 {object} jsonresult.JSONResult{data=string} "desc"
// @success 200 {object} jsonresult.JSONResult{data=[]string} "desc"
```
please see generated result in testcases of this PR.
https://github.com/swaggo/swag/issues/650
=> Support response model composition 

README.md, operation.go, operation_test.go, parser.go
Describe the PR
fix bug: int,int32,int64, etc. are not replaced with integer in output docs, PR by #651
feature: support multiple fields overriding.
fix #657 
Relation issue
#650
#651
#657
=> issue 650: fix integer bug in response; support multi fields overriding.

example/celler/controller/examples.go
fixed this error
```
ParseComment error in file controller/examples.go :can not find schema type: "controller.integer"
```
#659
n
=> [FIX] parse comment error integer to string

parser.go, parser_test.go, testdata/json_field_string/main.go, testdata/non_exported_json_fields/main.go, testdata/simple2/web/handler.go
In order to match encoding/json behaviour for Marshaling struct into JSON, we should not parse non-exported fields (aka: fields starting with a lower letter)
https://github.com/swaggo/swag/issues/666
With this commit, I had to apply a small fix to a test. I really think it's ok, but please, verify it.
=> fix: parseField skips not-exported (encoding/json-like)

parser.go, parser_test.go, testdata/json_field_string/main.go
Fix the json example when a struct field has the `json:",string"` tag.
https://github.com/swaggo/swag/issues/665
encoding/json states:
> The "string" option signals that a field is stored as JSON inside a JSON-encoded string. It applies only to fields of string, floating point, integer, or boolean types. This extra level of encoding is sometimes used when communicating with JavaScript programs:
---
Before this fix, the provided example would fail json.Unmarshal:
After fix:
=> issue-665: fix example when using `json=",string"`

README.md, operation.go, operation_test.go, parser_test.go, testdata/non_exported_json_fields/main.go
Recursively parse content in { } to overriding deep-level fields in response object，also support map.
Enhancement of #650
#670  
#676
=> Overriding deep-level fields in response object

parser.go, testdata/alias_import/data/applicationresponse.go, testdata/alias_import/expected.json, testdata/alias_import/types/application.go
**Issue**
For example, there's a package `github.com/user/repo/common` which contains type `Common`:
```go
package common
type Common struct {
ID int `json:"id"
}
```
If we embed this type in another struct but use an alias instead of the real package name, **swag** will generate wrong documentation:
```go
package main
import (
c "github.com/user/repo/common"
)
type Response struct {
c.Common
Name string `json:"name"
} 
```
Generated documentation:
```json
{
"definitions": {
"main.Response": {
"type": "object",
"properties": {
"name": {
"type": "string"
}
}
}
}
}
```
**Solution**
We can suppose that `pkgName` is a package alias, if [`typeSpec`](https://github.com/swaggo/swag/compare/master...ShoshinNikita:master#diff-f615844d3497ff38db57e459d6ef657bR861) is `nil`. So, we can just iterate …
=> Fix issue with generating docs for embedded structures with alias instead of package name

gen/gen.go, gen/gen_test.go, operation.go, parser.go, parser_test.go, schema.go
=> refactor step1： build spec.Schema; parse object in request

go.sum, parser.go, parser_test.go, testdata/conflict_name/api/api1.go, testdata/conflict_name/api/api2.go, testdata/conflict_name/expected.json, testdata/conflict_name/main.go, testdata/conflict_name/model/model.go, testdata/conflict_name/model2/model.go
rename all the name-conflicted models for a stable parsing result.
#745
=> stable renaming to fix issue #745; uncapitalize tow members of parser

README.md, README_zh-CN.md, example/celler/controller/examples.go, operation.go, operation_test.go, testdata/simple/api/api.go, testdata/simple2/api/api.go, testdata/simple3/api/api.go
Fixes "maximum" needing to be "maxinum" to work, and "minimum" needing to be "mininum" to work.
Retains support for the old field names and adds tests to ensure the old names continue to work.
Fixes https://github.com/swaggo/swag/issues/761
=> Fix typos in maximum/minimum attributes

cmd/swag/main.go, gen/gen.go, parser.go, parser_test.go
add parseDepth flag for speed up generate
on my laptop right parseDepth flag give ~x3 speed up (1m -> 23sec)
=> Parse depth

parser.go, parser_test.go, testdata/composition/expected.json, testdata/conflict_name/expected.json, testdata/nested/expected.json
Avoid generate license field with empty content in generated YAML and JSON files when running `swag init`
Intended to resolve #767
Let me know if you need any additional info
=> fix: don't generate license field if it's empty

operation.go
Allow generate params for formData by using go struct.
Intended to resolve https://github.com/swaggo/swag/issues/300
`go test` passed even if I didn't change anything related to the unit test, it seems the old test doesn't cover this case. I didn't add any extra test cases for this PR since I'm not sure about how to write unit test for this case. Hope that's okay.
btw if this PR can get merged, the documentation may also need to update.
=> feat: generate formData params via go struct

.gitignore
The `.gitignore` rule `swag` matches not only file in main directory but also folder in `cmd/swag`.
I've changed it to match only in current folder. For visual I've changed also `swag.exe`.
I've run into the issue when I tried to vendor sources for swag but also for tool. The `main.go` got ignored by git, I've forced git to add it with `git add -f vendor/github.com/swaggo/swag/cmd/swag/main.go`
https://git-scm.com/docs/gitignore#_pattern_format
> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.
=> Ignore swag file from root dir only

parser.go, parser_test.go
This PR adds ability to set `swaggerignore:"true"` on embedded fields.
https://github.com/swaggo/swag/issues/632 
Currently `swaggerignore` supports only ignoring named fields, while in some cases it is also useful to be able to ignore embedded fields.
=> Add ability to set 'swaggerignore' on embedded fields

example/celler/model/account.go, go.mod, go.sum, testdata/simple/web/handler.go, testdata/simple2/web/handler.go, testdata/simple3/web/handler.go
Replace non-maintained and vulnerable satori/go.uuid with its successor - gofrs/uuid
https://github.com/satori/go.uuid
satori/go.uuid security issue:
https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488
https://github.com/swaggo/swag/issues/799
-
=> replace unsupported and vulnerable satori/go.uuid with gofrs/uuid

operation.go
Instead of always sorting parameters with name, which can surprise users
because x-order is ignored, sort them with the slice type declared in
github.com/go-openapi/spec to reuse its comparison method.
https://github.com/swaggo/swag/pull/681
It can be simplified if https://github.com/go-openapi/spec/pull/117 is merged.
=> fix: honor x-order while sorting query parameters

README.md, cmd/swag/main.go
--generatedTime was documented as true by default, although immediately
after we stated that it was false by default.
Also capitalized the --exclude docs, and updated README.md's output for
consistency.
None, this is just a cosmetical fix.
P.D.: great tool!
=> Update CLI flags docs

go.mod, go.sum, operation_test.go, parser_test.go, testdata/simple/expected.json
Upgrade github.com/go-openapi/spec and golang.org/x/tools to latest
versions.
Upgrading github.com/go-openapi/spec v0.19.11 -> v.0.19.14 generates
empty "description" members for responses and empty "authorizationUrl"
members for securityDefinitions when they're missing. This causes tests
to fail. Fix by adding the missing empty definitions to expected test
results.
Since travis-ci test builds always fetch deps and build before running tests,
they break because of the change in go-openapi/spec
=> Update dependencies and fix tests

schema.go, schema_test.go
Not requiring an additional parameter to be set when using `object` in `swaggertype`.
https://github.com/swaggo/swag/issues/843
=> Optional additional parameter when using object in swaggertype

.goreleaser.yml
Added ARM64 architecture to .goreleaser.yml for releasing Linux/ARM64 binary.
Signed-off-by: odidev <odidev@puresoftware.com>
Resolves #841 
N/A
=> Release swag for Linux/ARM64

example/object-map-example/go.mod
Update gin-swagger dependency version to mitigate issue with missing dep (github.com/ugorji/go v1.1.5-pre).
Issue link: https://github.com/swaggo/swag/issues/826
=> Update example go.mod (example/object-map-example/go.mod)

operation.go, operation_test.go, version.go
Repair the regular expression for full response
fix #855
#853 ,  #855
=> change the regular expression to fix the issue #853 caused by PR #837

README.md
Add an example of add a description for enum items
None
None
=> Add an example of add a description for enum items

README.md, README_zh-CN.md
Update documentation regarding go compatibility
https://github.com/swaggo/swag/issues/913
NONE.
=> update documentation regarding go version

gen/gen.go, gen/gen_test.go
- fix a typo.
- remove impossible condition
=> fix gen_test.go

operation.go, operation_test.go
Adds support for including enums on array query parameters. If the parameter type is an array, the enum values are added to the items field on the parameter instead.
https://github.com/swaggo/swag/issues/918
None
=> Support enums on array parameters

README.md, operation.go, operation_test.go, parser.go, parser_test.go
Add support to specify multiple routes for the same function
https://github.com/swaggo/swag/issues/460
In the case of multiple @Router comments, swagger creates routes using information only from the last comment.
This change would help us add swagger routes for each comment.
=> Add support to specify multiple routes for the same function

operation.go, operation_test.go, packages.go, parser.go, parser_test.go, schema.go, schema_test.go, testdata/api.md, testdata/markdown.go, testdata/users.md
Improve test coverage and code readability.
#921 - this issue reduced the code coverage after merging .
CI didn't work for some reason and there was no CodeCove report.
NONE
=> Improve test coverage and code readability.

gen/gen.go, gen/gen_test.go, packages.go, parser.go, parser_test.go, testdata/duplicate_route/api/api.go, testdata/duplicate_route/main.go
Fixes issue when you accidentally have `@Router /some/route` declared twice.  
Previously this would cause either of the 2 definitions to be used and it leaves the user very confused.
Tbh I'd personally just prefer the hard error when this mistake is made, but I think for backwards compatibility it might be nice to either have it warn by default (as it is now in this PR) or have the option to turn it into a warning, so I added the `Strict` option flag.  
I think this could also be useful for more checks in the future?  
Additionally I made `RangeFiles` sort the files to make sure it happens in deterministic order, prior to my fix to warn / error when there's a duplicate route and without this you'd randomly get one of the 2 routes and that *really* confuses the hell of you because instead …
=> Handle duplicate route declaration better

parser.go, parser_test.go, testdata/main.go
Relates to issue #970.
Before this PR the only `@x-` attribute supported on the security definition was the hardcoded `x-tokenName`. After this PR all the `@x-` attributes that are parsed in the same block than the security definition are going to be added.
Added extra logic for not adding twice the `@x-` attributes that are present on the security definition and removed the hardcoded case scenario for token name as well.
=> Added support for @x- attributes on security definition

README.md, README_zh-CN.md, parser.go, testdata/simple/expected.json, testdata/simple/web/handler.go
This change supports to use boolean false value as extension values. Currently, extensions field only supports boolean true and string values. However, boolean false value is needed for some frequently used extensions such as `x-omitempty`.
All swagger extensions should start with `x-`, so prefix `!` does not break anything and it can be a good rule.
None
My first approach was like `x-omitempty=false`, but it may break some extensions that uses `false` as string value.
=> support boolean false value in extension

parser.go, parser_test.go, testdata/json_field_string/main.go, testdata/simple/expected.json
The format tag used on an array type should place the format in the items object, rather than directly on the type.
Examples of this are available on the Swagger website, under **Array Examples** [here](https://swagger.io/docs/specification/adding-examples/).
```yaml
components:
schemas:
ArrayOfInt:
type: array
items:
type: integer
format: int64
example: 1
```
```yaml
components:
schemas:
ArrayOfInt:
type: array
items:
type: integer
format: int64
example: [1, 2, 3]
```
=> Correctly parse format on array fields

operation.go, operation_test.go, schema.go
Add support for "nil" type for the empty response
#941 
NONE
=> add support for empty response

README.md, parser.go, parser_test.go, testdata/pet/web/handler.go, testdata/simple/expected.json, testdata/simple/web/handler.go, testdata/simple2/web/handler.go, testdata/simple3/web/handler.go
Describe the PR
Add ability to specify multipleOf struct field
Relation issue
N/A
----
Sorry, ran into an issue and needed to reopen
=> Add multipleOf field to parser.

field_parser_test.go, operation.go, operation_test.go, parser.go, parser_test.go
Support `go-playground/validator`.
Support for parsing more tags of validator, such as  max\min\oneof. 
example: 
```
type JsonResponse struct {
Errno  int         `json:"errno" validate:"required,max=1000,min=10"`
ErrMsg string      `json:"errmsg" validate:"required,max=1000,min=10,oneof=success fail"`
Data   interface{} `json:"data"`
}
```
after:
```
{
"response.JsonResponse": {
"type": "object",
"required": [
"errmsg",
"errno"
],
"properties": {
"data": {},
"errmsg": {
"type": "string",
"maxLength": 1000,
"minLength": 10,
"enum": [
"success",
"fail"
] 
},
"errno": {
"type": "integer",
"maximum": 1000,
"minimum": 10
}
}
}
}
```
https://github.com/swaggo/swag/issues/995
=> feat: support go-playground/validator tags.

cmd/swag/main.go, field_parser.go, field_parser_test.go, gen/gen.go, gen/gen_test.go, operation.go, operation_test.go, packages.go, parser.go, parser_test.go, schema.go, swagger.go, types.go
* improve code quality
* clean some typos
* align structure data to use less memory
NONE
NONE
=> improve code quality

.github/workflows/ci.yml, field_parser.go, field_parser_test.go, gen/gen_test.go, operation.go, operation_test.go, packages.go, parser.go, parser_test.go, testdata/simple/api/api.go, testdata/simple/expected.json
fix bug and refactor
duplicate enums item when tag enums , binding or validate appear at the same time
no
=> fix bug and refactor

operation.go, operation_test.go
improve code quality
NONE
NONE
=> chore: improve code quality

operation.go, operation_test.go
Add `$` to valid router paths for compatibility with HL7 FHIR standard. 
The FHIR standard uses $ to prefix operations against compliant endpoints. [Section 3.2.0.1 of the FHIR specification](https://www.hl7.org/fhir/operations.html#executing) gives a definition and an example. Allowing $ as a modifier would enable teams working in Go to output Swagger specifications for APIs that interact with FHIR endpoints and further the goal of greater healthcare data interoperability around the world.
**More information about HL7 FHIR standard**
HL7 is a multinational non-profit organization that defines interoperability and messaging standards for the healthcare industry. The following countries use an HL7 defined specification as the primary method for messaging between …
=> add dollar sign to acceptable router paths

operation.go, operation_test.go
fix: allways init response header map at first.     
- to generate headers only "all".   
- fix PR https://github.com/swaggo/swag/pull/1049
- refactor  
closes [#1065](https://github.com/swaggo/swag/issues/1065)
=> fix: allways init response header map at first.

operation.go, operation_test.go
fix issue introduced during code refactor
#1067
none
=> fix: parsing panics on default response

formater.go, formater_test.go, parser.go
remove duplicated walk function
NONE
NONE
=> chore: remove duplicate walk func

format/format.go
This will remove the check for existence of the `SearchDir` on `swag fmt` which is breaking the comma separated list feature from `swag fmt -d cmd/hello,./`, fore example.
The check is being made after splitting the list on the comma character, later, in the `FormatAPI` call.
=> chore:remove unnecessary check

.github/workflows/ci.yml, README.md, README_zh-CN.md
Drop support for GO 1.13
None
The pipeline is taking too long to run all 1.13-1.17 Linux and macOS tests.
=> chore: drop support go 1.13

field_parser.go, operation.go
reduce the number of hardcoded tags.
None
None
=> chore: field tags constants

README.md, cmd/swag/main.go, gen/gen.go, gen/gen_test.go
**This PR propose one new feature and fix:**
- Feature: Possibility to specify which docs file to generate - `go` or `json` or `yaml`. Defaults preserved to all file types.
- Fix: Typo for file name and space before parentheses in cmd package.
**Reason for implemented feature:**
Needed because I created my own handler for serving static files and the only file I need to show Swagger UI for my API is `docs.go`. I don't need other files, because I'm setting basic project/docs variables (name, version, description, ...) dynamically at the start of API/Docs server and after `swag init` they are not fully correct (as expected).
=> Specific docs file type write

README.md, parser.go, parser_test.go, testdata/struct_comment/web/handler.go
Added "description" field generation for swagger scheme from struct documentation
https://github.com/swaggo/swag/issues/708
None
=> feat: add generation of type description to schema (#708)

gen/gen.go, gen/gen_test.go
Feature: Generated file name from instanceName
=> Feature: Generated file name from instanceName

.github/workflows/ci.yml, README.md, README_zh-CN.md
drop support for go 1.14
None.
None
=> chore: drop support for go 1.14

operation.go, operation_test.go
Add example value to parameter
#1119
None.
=> feat: add example parameter

field_parser.go, field_parser_test.go
allow empty example strings for struct fields 
#1102
None.
=> feat: allow empty example strings for struct fields

field_parser.go, field_parser_test.go, operation.go, parser_test.go
split extensions param respecting open/close brackets
`// @Param range query string true "Range" default([0, 9]) extensions(x-example=[0,9])`
None.
When using extensions param with text containing comma the extensions were getting splited wrong.
=> fix: split extensions param respecting open/close brackets

operation.go, operation_test.go
=> #1140 added SchemaExample() to set the example to schema

operation.go, operation_test.go
Feature to generate OR-security option for swagger files.
[e.g. https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1149)
Sorry for not waiting for any approval Was watching at the source code and almost accidentally coded this.
I desperately need this function to make this repo useful for my company.
=> [security] feature add or-option

README.md, operation.go, operation_test.go
=> feat: SchemaExample: allow \r \n \t

README.md
Add `example` param details to the README.md. 
#1119
The support for the parameter was added at #1122, at scope of #1119, but there are no details about this flag at the README. To find this details, I was needed to look at the related issues, so I've decided to add this details to the README to simplify searches for others who may need this feature
=> impr: add param example to readme

example/celler/controller/examples.go
Corrected @Produce comments according to code
https://github.com/swaggo/swag/issues/1195
=> Correct  @Produce comments in examples

cmd/swag/main.go, gen/gen.go, golist.go, golist_test.go, packages.go, packages_test.go, parser.go, parser_test.go, testdata/golist/api/api.go, testdata/golist/api/foo.c, testdata/golist/api/foo.h, testdata/golist/main.go, testdata/golist_disablemodule/api/api.go, testdata/golist_disablemodule/api/foo.c, testdata/golist_disablemodule/api/foo.h, testdata/golist_disablemodule/main.go, testdata/golist_invalid/main.go, testdata/invalid_external_pkg/invalid/normal.go, testdata/invalid_external_pkg/main.go
Directly use `go list` command instead of `depth`, because `depth` use go standard library `build.Import`  and call the `build.Import` too many times, it will spent too many times when the large dependencies.
Because `swag` only needs to know which files are dependent, and does not need to get the level of dependencies, all dependencies can be directly through `go list` command, and `swag` not need to go through deep loop again, but if use `depth`, `swag` still need to loop too many times, so i refactor the swag get ast files code.
Fixes: https://github.com/swaggo/swag/issues/1032
Added the `--parseGoList` flag, the default value is true default. If someone does not want to enable it, it can be set to false when init, if it's …
=> Imporve performance when generating spec with external dependencies

cmd/swag/main.go, gen/gen.go, gen/gen_test.go, parser.go
Add a `--quiet`=true flag for `swag init`.
make the debug logger quiet.
https://github.com/swaggo/swag/issues/1193
=> add --quiet=true for swag init, make the debug logger quiet.

gen/gen_test.go, parser.go, parser_test.go, schema.go, schema_test.go, testdata/error/api/api.go, testdata/error/errors/errors.go, testdata/error/expected.json, testdata/error/main.go, testdata/error/web/handler.go
This manage error and any like interface. 
Previously, any would result in a primitive type `any` which seem not valid in swagger definition.
This basically, set an empty definition like for `interface{}` previously for `any` and `error` types.
- https://github.com/swaggo/swag/pull/1188
- https://github.com/swaggo/swag/issues/1171
- https://github.com/swaggo/swag/issues/1131
This fix cases when you cannot override with tag `swaggertype` in case the struct is from an external dependency. 
Previously this case need to redefine the struct locally to override the field type but can be cumbersome in case of deeply nested struct and It is also not possible to override go types with  .swaggo file.
I first try to implement like suggested in [this …
=> Implement error (and any) like interface

operation.go, operation_test.go, parser_test.go
Add default description to code if none is provided
#1218
=> add default description to code if none is provided

README.md
Update repository URL for Fiber Swagger (the repository was moved there).
The repository https://github.com/arsmn/fiber-swagger is deprecated.
=> Update repository URL for Fiber Swagger

format/format.go
Fix temp file logic t avoid invalid cross-device link 
https://github.com/swaggo/swag/issues/1203
**Cause**
This  error  occurs when os.Rename between different partitions
https://groups.google.com/g/golang-dev/c/5w7Jmg_iCJQ
In other words, TMPDIR and PWD  are different partitions.
When  `ioutil.TempFile(dir, pattern string)` 's first parameter is empty string, TempFile are created on TMPDIR.
> If dir is the empty string, TempFile uses the default directory for temporary files (see os.TempDir).
https://pkg.go.dev/io/ioutil#TempFile
**Solution**
Fix `filepath.Split()` to `filepath.Dir() and Base()`.     
`filepath.Split` may return an empty string.
```go
package main
import (
"fmt"
"path/filepath"
)
func main() {
paths := …
```
=> fix: temp dir to be the same as SerchDir to avoid invalid cross-device link (#1203)

parser.go, parser_test.go
`Parser.Skip()` treats `..` directory as hidden folder and return a `filepath.SkipDir`. If `..` is provided via `--dir` option, `swag` will miss some files.
=> fix: don't skip ".." directory

generics.go, generics_test.go, testdata/generics_arrays/api/api.go, testdata/generics_arrays/main.go, testdata/generics_arrays/web/handler.go
Fixed generic nested array generation.
[#1246 ](https://github.com/swaggo/swag/issues/1246)
=> fix: generic arrays generate successfully

formatter.go, formatter_test.go
Fix issue https://github.com/swaggo/swag/issues/1150
To summarize the issue, running `swag fmt` will set (at least) 2 spaces between the attribute tag and the rest of the comment. But this is a problem for struct with single comment:
```diff
type Example struct {
Foobar string
-} // @name Example
+} // @name  Example
```
Indeed the doc generation doesn't interpret this correctly for struct (it completely ignore it).
So there are 2 solutions:
- fix the indent (which is feel more natural)
- fix the doc generation to correctly parse 2 spaces
This commit is fixing the indent part.
Basically I just set the padding=1 on `tabwriter`.
The cons is that it will also impacts all other godocs.
For instance (taken from the readme):
```diff
-// @title           Swagger Example API
-// @version …
```
=> fix: fmt issue with struct

README.md, README_zh-CN.md, parser.go
Add missing framework links
#98 
None
=> doc: add missing web frameworks

cmd/swag/main.go, gen/gen.go
Fixes an issue where certain debug logs were always directed to `stderr`, even if the `-q` flag was provided.
#1255 
This fix will be helpful for anyone who wants to suppress all debug output (e.g. when generating API docs as part of a git commit hook).
I took the path of least resistance here since I'm not sure on the development philosophy for this project. For example, I initialized the new `Gen.debug` field in the `Build()` method instead of the `New()` method. Happy to pass the debugger in as an arg to `New()` instead if that's preferred.
I did run the changes and they work as expected.
=> fix: suppress debug logs when using -q

gen/gen_test.go, generics.go, generics_test.go, testdata/generics_arrays/api/api.go, testdata/generics_arrays/expected.json, testdata/generics_arrays/types/post.go, testdata/generics_arrays/web/handler.go, testdata/generics_basic/.swaggo, testdata/generics_basic/api/api.go, testdata/generics_basic/expected.json, testdata/generics_basic/types/post.go, testdata/generics_basic/types/string.go, testdata/generics_basic/web/handler.go, testdata/generics_names/api/api.go, testdata/generics_names/expected.json, testdata/generics_names/types/post.go, testdata/generics_names/web/handler.go, testdata/generics_nested/api/api.go, testdata/generics_nested/expected.json, testdata/generics_nested/types/post.go, testdata/generics_nested/web/handler.go, testdata/generics_property/expected.json, testdata/generics_property/types/post.go, testdata/generics_property/web/handler.go
PR fixes the issues  described in https://github.com/swaggo/swag/issues/1237 and https://github.com/swaggo/swag/issues/1253
Additionally, it reduces the generated doc size, cause it creates refs to types instead of embedding the fields
https://github.com/swaggo/swag/issues/1237
https://github.com/swaggo/swag/issues/1253
All changes are backward compatible and have been tested with Go 1.15, 1.16, 1.17, 1.18 and 1.19.
=> fix: Go generics cannot find common package object type definition

packages.go, packages_test.go, parser.go, parser_test.go, schema.go, schema_test.go, testdata/duplicated_function_scoped/api/api.go, testdata/duplicated_function_scoped/main.go, testdata/duplicated_function_scoped/other_api/api.go, testdata/simple/api/api.go, testdata/simple/expected.json, types.go
I added the functionality of parsing function scoped structs.
With this development we will be able to define our request response types in the same function scope as our handlers:
```
package main
// @Param request body main.Fun.request true "query params" 
// @Success 200 {object} main.Fun.response
// @Router /test [post]
func Fun()  {
type request struct {
Name string
}
type response struct {
Name string
Child string
}
}
```
https://github.com/swaggo/swag/issues/1274
All tests passed in parser_tests.go. Changes look backward compatible.
=> add functio scoped struct parse, tests

.goreleaser.yml
Binaries that are being built by the goreleaser don't have the CGO_ENABLED=0 env set which means they are dynamically linked to 
/lib64/ld-linux-x86-64.so.2  (or whichever version of ld-linux)
In some versions of distros, there are different versions ld-linux which makes the swag not start properly. 
In my case, I wanted to download the release binary into intermediate docker based on alpine to generate API documentation and it was always failing with "file not found" error.
NOTE: This change was not tested - I don't have the whole setup to test the goreleaser
sources:
https://jvns.ca/blog/2021/11/17/debugging-a-weird--file-not-found--error/
https://goreleaser.com/customization/build/
Add CGO_ENABLED=0 into .goreleaser
=> Set env CGO_ENABLED=0  for goreleaser to avoid dynamic linking

swagger.go, swagger_test.go
Problem starts if our swagger instance generated by CI and registered.
In main program if we want to modify some parameters inside of that instance is it not possible because code not in there.
Getting swagger instance with name from register it is easy to work with it, without need any workaround.
Swagger is an interface so we should do some casting but we know the our code and it should be this type.
```go
if s, ok := swag.GetSwagger("swagger").(*swag.Spec); s != nil && ok {
s.Version = "1.0.0"
s.Title = "Test"
}
```
#1240
=> feat: get swagger instance from register

README.md
Update README documentation
https://github.com/swaggo/swag/pull/1283
=> update readme add function scoped struct decleration example

packages.go
Nil pointer check in function scoped types.
#1309 
This is fixes problem on running swag build.
=> fix: funcDeclaration body check

generics.go, generics_other.go, generics_other_test.go, generics_test.go, packages.go, parser.go, testdata/generics_property/api/api.go, testdata/generics_property/expected.json, testdata/generics_property/main.go
Fixes Bug described in https://github.com/swaggo/swag/issues/1306
- Support for *ast.IndexExpr added to Parser.parseTypeExpr
- tests extended to cover use cases
https://github.com/swaggo/swag/issues/1306
All changes are backward compatible and have been tested with Go 1.15, 1.16, 1.17, 1.18 and 1.19.
=> fix: Generic Fields does not handle Arrays

formatter.go, formatter_test.go
Fixes formatting crosstalk (https://github.com/swaggo/swag/issues/1314) by modelling and applying formatting changes as byte-range edits rather than find/replace operations, which could accidentally clobber identical (correctly-formatted) comment lines.
Resolves https://github.com/swaggo/swag/issues/1314.
**Additional comments**
Of course, everyone's experience will vary, but in the codebase I'm working in with – 4,132 attribute comments across 450 comment groups – this fix changes 8 comment lines. Those changes are pretty obvious and desirable, but I also don't anticipate that this will generate huge waves of changes in existing codebases.
=> Fix formatting crosstalk

generics_test.go, operation.go, parser.go, testdata/generics_basic/.swaggo, testdata/generics_basic/expected.json, testdata/generics_basic/types/string.go
Fixes Bug described in https://github.com/swaggo/swag/issues/1318 and https://github.com/swaggo/swag/issues/1320
- https://github.com/swaggo/swag/issues/1318
- https://github.com/swaggo/swag/issues/1320
Since I did not find any suitable tests, I integrated them into the generics tests.
Tested with Go 1.15, 1.16, 1.17, 1.18 and 1.19.
=> fix: Generic Fields does not handle Arrays in the .swaggo file

packages.go, testdata/generics_basic/api/api.go, testdata/generics_basic/expected.json
Fixes bug described in https://github.com/swaggo/swag/issues/1319
- Generic detection moved to own method
- prepend pkg name if not provided
https://github.com/swaggo/swag/issues/1319
Tested with Go 1.15, 1.16, 1.17, 1.18 and 1.19.
=> fix: Generics not detected if name does not contain a pkg name

.github/workflows/docker.yml
build a docker image and push it to ghcr.io
#1276
None
=> build a docker image and push to ghcr.io

operation.go
add support formData multiple file
https://github.com/swaggo/swag/issues/866
=> feat. add support formData []file

cmd/swag/main.go, format/format.go, format/format_test.go, gen/gen_test.go, generics_test.go, operation.go, parser.go, parser_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://pkg.go.dev/io/ioutil). Since we have dropped support for Go 1.15 and lower (https://github.com/swaggo/swag/pull/1331), we can replace the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
- `ioutil.Discard` => `io.Discard`
- `ioutil.NopCloser` => `io.NopCloser`
- `ioutil.ReadAll` => `io.ReadAll`
- `ioutil.ReadDir` => `os.ReadDir` (returns a slice of `os.DirEntry` rather than a slice of `fs.FileInfo`, this may improve performance in some cases as `os.ReadDir` is more efficient [\[1\]])
- `ioutil.ReadFile` => `os.ReadFile`
- `ioutil.TempDir` => `os.MkdirTemp`
- `ioutil.TempFile` => `os.CreateTemp`
- `ioutil.WriteFile` => `os.WriteFile`
[\[1\]]: …
=> refactor: move from io/ioutil to io and os packages

generics.go, generics_other.go, generics_other_test.go, generics_test.go, packages.go, testdata/generics_property/api/api.go, testdata/generics_property/expected.json
I don't know how to discribe this issue, but just fix it.
#1346
=> fix issue #1346 about generics

generics.go, generics_other.go, generics_test.go, parser.go, testdata/generics_property/api/api.go, testdata/generics_property/expected.json, testdata/generics_property/types/post.go
fix generic bug:  a struct field with complex generic type.
for example:
```
type MyFieldStruct[T1 any, T2 any] struct {
Data1   T1
Data2   T2
}
type Nested[T any] struct{
Value T
}
type MyStruct[T any] struct{
Field1 *T
Field2 []T
Field3 MyFieldStruct[T, string]
field4  Nested[Nested[string]]
}
```
#1345
=> Fix generics issue #1345 

.github/workflows/ci.yml, .github/workflows/docker.yml
Update action versions
None
Deprecation of v2 actions 
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-go
 
<br class="Apple-interchange-newline">
=> chore: update GitHub actions

example/basic/api/api.go, example/basic/main.go, example/celler/controller/accounts.go, example/celler/controller/admin.go, example/celler/controller/bottles.go, example/celler/controller/examples.go, example/celler/main.go, example/go-module-support/main.go, example/markdown/api/api.go, example/markdown/main.go, example/object-map-example/controller/api.go, example/object-map-example/main.go, example/override/handler.go, example/override/main.go, formatter.go, formatter_test.go
=> make swagger comments more readable for go doc

packages.go
[e.g. https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1368)
This PR solve the problem
=> Add check for nil otherTypeDef

example/basic/api/api.go, example/basic/main.go, example/celler/controller/accounts.go, example/celler/controller/admin.go, example/celler/controller/bottles.go, example/celler/controller/examples.go, example/celler/main.go, example/celler/model/account.go, example/go-module-support/main.go, example/markdown/api/api.go, example/markdown/main.go, example/object-map-example/controller/api.go, example/object-map-example/main.go, example/override/handler.go, example/override/main.go, formatter.go, formatter_test.go
change fmt cmd: use a tab instead of two spaces at the front of a comment line, to be compatibale with gofmt v1.19.
#1381
=> fmt cmd: use a tab instead of two spaces to format comments

README.md, cmd/swag/main.go, gen/gen.go, parser.go, parser_test.go
Added CLI flag to generate the doc for them if specified.
It helps when you want to generate multiple pieces of documentation(e.g. one for devs and a separate one for customers)
None
ToDo:
=> Add flag to generate documentation only for specifics tags

parser.go, schema.go
If there are more than two fields with the same redefined type which especially based on a primitive type, they will share a schema in fault. If one of them modified the schema, another will be affected.
fix :  every field gets a copy of the schema unless the schema is a ref schema,  and then complete it with field properties.  
#1342
=> fix: wrongly shared schema by fields

const.go, enums.go, gen/gen.go, generics.go, generics_other.go, generics_other_test.go, generics_test.go, package.go, packages.go, packages_test.go, parser.go, parser_test.go, testdata/enums/consts/const.go, testdata/enums/types/model.go
Enhancement for PR #1387:  evaluate const across packages
#1367
=> enhancement for PR #1387:  evaluate const across packages

field_parser.go, parser.go, testdata/simple/expected.json
This change makes it so json tags on embedded structs are honored.
One example of this:
```go
type RevValueBase struct {
Status bool `json:"Status"`
Err int32 `json:"Err,omitempty"`
}
type RevValue struct {
RevValueBase `json:"rev_value_base"`
}
```
Previously, `RevValueBase` was inlined into `RevValue`. With this change, it matches the behavior of the core json package and the embedded struct becomes a field.
```json
"rev_value_base": {
"$ref": "#/definitions/web.RevValueBase"
}
```
It should be noted that this changes the schema generation of embedded structs. However, since it was impossible to unmarshal embedded structs previously, I don't believe this is could cause breakage unless people implemented custom de-serialization.
Fixes #886
=> support json tags in embedded structs

formatter.go, formatter_test.go, operation.go, parser.go, testdata/enums/expected.json, utils.go, utils_test.go
1. During parsing comments, use func `unicode.IsSpace`  instead of a space ' ' to split.
2. When spliting comments during formating, don't split nested pair characters such as [] in generics example `A[[]B,[]C]`
#1397
=> fix parsing bug affected by fmt

packages.go, packages_test.go, parser.go, parser_test.go, types.go
sometimes, we want to know where the error is when parsing go files, so record token.FileSet for every file so that the position of parsing error can be acquired and output to log
#1392
=> enhancement: record token.FileSet for every file

parser.go
Just optimize code about parsing extensions
=> Just optimize code about parsing extensions

parser.go, parser_test.go
Replaces the regular string splitting by a ":" made during the "example" tag parsing so that it will not split escaped double colons, allowing string examples containing a double colon to be escaped using double backlashes.
https://github.com/swaggo/swag/issues/1401
Since the core `regexp` library cannot suport negative lookaheads, I had to combine a regular expression with a loop to capture all the ocurrences and append them to an array.
=> chore: parse escaped double colon (\\:) example struct tag

const.go, enums_test.go, package.go, testdata/enums/consts/const.go, testdata/enums/main.go, testdata/enums/types/model.go, utils_go18.go, utils_other.go
1. explicit enum conversion;
2. implicit integer conversion;
3. keep the type of the right operand of a shift operation;   fix #1392  `negative shift amount` as a result of expression `^uint(0)`
4. parse escape characters.    
5. rune type in binary expressions. fix #1392  `interface{} is nil, not int`  
6. function len to get the length of a literal string
7. parse hex and oct numbers
#1392 
examples:
```
const uintSize = 32 << (^uint(uintptr(0)) >> 63)
const maxBase = 10 + ('z' - 'a' + 1) + ('Z' - 'A' + 1)
const shlByLen = 1 << len("aaa")
const hexnum = 0xFF
const octnum = 017
const nonescapestr = `aa\nbb\u8888cc`
const escapestr = "aa\nbb\u8888cc"
const escapechar = '\u8888'
type Class int
const A Class = 1
const B = Class(2) 
```
=> enhancement for enums

parser.go, parser_test.go, testdata/parseExtension/parseExtension.go
parseExtension will break on empty comment lines `//`
https://github.com/swaggo/swag/pull/1219
My previous test cases weren't covering empty comment lines and in that case `fields[0]` breaks.
Added fix and tests.
More than open for further suggestions/improvements if there are any
=> fix: don't error on empty comment line in matchExtension

parser.go, parser_test.go
split security attribute with any space character
#1414
=> fix issue 1414

operation.go, parser.go, testdata/enums/api/api.go, testdata/enums/expected.json
=> feat: use enums in request

README.md
This PR adds an explanation about the need for doc comments in addition to swagger comments when using `swag fmt`. 
Documentation for a rare issue that can occur since swag is now formatting with tabs since #1386.
=> docs: explain the need for doc comments when using swag fmt

golist.go, packages.go, packages_test.go, parser.go, parser_test.go, types.go
No longer parse operations in dependency, just parse models 
#1430
=> Do not parse operations in dependency

gen/gen.go
Remove duplicate space in
```log
2023/01/05 17:51:16 create docs.go at  docs/docs.go
2023/01/05 17:51:16 create swagger.json at  docs/swagger.json
2023/01/05 17:51:16 create swagger.yaml at  docs/swagger.yaml
```
=> style: remove duplicate space

packages.go
Here we are going to trim `//`, `/*` at the comment before and `*/` last, should use `TrimPrefix` and `TrimSuffix` instead of `TrimLeft` and `TrimRight`.
None
=> fix: string cutset method usage

README.md, README_zh-CN.md, parser.go, parser_test.go, testdata/main.go, testdata/templated.go
Support externalDocs annotation comment.
https://github.com/swaggo/swag/issues/470
=> Support externalDocs annotation comment

operation.go, operation_test.go
If the top type name in response is any or interface{}, don't use allOf. This will make it more readable.
#1413
=> if the top type name is any or interface{}, don't use allOf

field_parser.go, operation.go
swaggo doesn't look at the `form` tag on structs to determine field names, only the `json` tag. This update sets the field name in the swagger files to the `form` tag if it exists. This will match what gin binds to.
This issue was also raised here:
https://github.com/swaggo/swag/discussions/1411
=> Use form tags when available

README.md
The file data type will add the file input to the swagger ui when making a form data request with a file
e.g. add cool parser.
=> Added file data type

parser.go
Additional error message when parsing type definition
```
2023/03/06 18:51:36 Generating datalayer.UpdateInput
-> 2023/03/06 18:51:36 parse type error in 'datalayer.UpdateInput': cannot find type definition: special.Extratype
2023/03/06 18:51:36 Skipping 'datalayer.UpdateInput', recursion detected.
```
When type definition not found in  `pkgDefs.packages` it shows error like there is some recursion detected, but there is a incorrect/confusing path to the type `special.Extratype` used in imports section: 
Used import path: 
`"github.com/company/go-special"`
Expected import path:
`"github.com/company/special"`
This error message helps to find the specific type that is causing the "recursion"
=> Additional error message when parsing type definition

generics.go, testdata/generics_basic/api/api.go, testdata/generics_basic/expected.json
fix bug:  alias type of  generc with multi formal params
#1489
=> fix alias type of generic with multi formal params

generics.go, testdata/generics_basic/api/api.go, testdata/generics_basic/expected.json
fix generic type that has more than 2 params with only one constraint type.
Before, we have only onsidered generic type format like [x any, y any], but missed  [x,y any].
#1490
=> fix generic type that has more than 2 params with only one constraint type

field_parser.go, operation.go, parser.go
This is a completed way to support form tag.
As the extensions of schema only marshal keys with prefix `x-` into json, so I just add the form tag name with key `form` into the schema extensions, and look it up when parsing @param.
And this way also doesn't affect the final output docs.
#1422
=> support form tag

Makefile, gen/gen.go, go.mod, go.sum
The package `github.com/ghodss/yaml` is no longer actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`. It is actively maintained by Kubernetes SIG, and also widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.
https://github.com/ghodss/yaml
https://github.com/kubernetes-sigs/yaml
=> chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

operation.go, testdata/enums/api/api.go, testdata/enums/expected.json, testdata/enums/types/model.go
Transform struct fields of array enum type to query/formData params
#1521
=> transform struct fields of array enum type to query/formData params

operationv3.go, operationv3_test.go
The current V2 branch parses RequestBody parameters into the parameter object and always defaults to application/json in requestBodies. 
With this pullRequest we are aware of accept headers and use the correct mimeType in the RequestBody for the most common mimeTypes.
Implement #1540 
In the future we should deprecate the use of the param comment for the body and create a new // @requestBody comment type to support all available fields
=> Support accept Header & Use RequestBody

operationv3.go, operationv3_test.go, parserv3.go
Add basic support for the produce comment.
The implementation is based on some assumptions and is only been done to be able to parse swaggo v1 comments.
#1550 
We should update the ```//@Success``` comment in the future to incorporate the changes and additional fields of open api v3.1.0.
The support of the produce comment is more of a workaround right now. 
Looking at the structure of the V3 data, i'd recommend either additional comment types or expanding the ```//@Success```.
=> V2: Support produce comment

enums_test.go, gen/gen_test.go, operationv3.go, operationv3_test.go, parser_test.go, parserv3_test.go, testdata/conflict_name/expected.json, testdata/generics_package_alias/internal/expected.json, testdata/v3/simple/api/api.go, testdata/v3/simple/main.go, testdata/v3/simple/web/handler.go
As guessed, some tests broke after the upgrade of the module to v2.
This fixes all tests that broke during that process
Also fixes #1554
=> V2: Fix tests after module upgrade

go.mod, version.go
Add retract statement to fix proxy.golang.org cache
#1561 
Accidentally pushed tags from wrong console window. The wrongfully pushed tags have already been deleted, but the goproxy cache already picked them up.
A new tag has already been published to fix fetching of the latest version for versions <v2.0.0
```To retract a version, a module author should add a retract directive to go.mod, then publish a new version containing that directive. The new version must be higher than other release or pre-release versions; that is, the @latest [version query](https://go.dev/ref/mod#version-queries) should resolve to the new version before retractions are considered. The go command loads and applies retractions from the version shown by …
```
=> add retract to fix proxy cache caused by accidentally pushed tags

README_pt.md
translate documentation to Portuguese add option to define model delimiters
https://github.com/swaggo/swag/pull/1499
=> docs: documentate to portuguese Add option to set template delimiters.

gen/gen.go, go.mod, go.sum
Fixed an error, that caused the docs.go to not be generated.
None.
Also fixed incorrect error return in genv3
=> V2: Fix template delims

README.md, gen/gen.go, go.mod, go.sum, parserv3.go, parserv3_test.go, testdata/v3/servers/main.go
Adding the @servers param to fill the servers object. 
None.
The additional properties of the object can be implemented in the future. This PR only targets the basic functionality.
This PR is based on the branch of #1572 and should therefor be merged after.
=> V2: Add Servers param

package.go, testdata/enums/consts/const.go
support enums of underscored number
#1580
=> fix bug: enums of underscored number

package.go, testdata/enums/consts/const.go
Bring latest change from master to v2 branch
=> v2: fix bug: enums of underscored number (#1581)

parser_test.go, types.go
A bug fix.
* using swag version v1.8.12
* did run `swag fmt ...` and custom type names got reformatted
* did run `swag init ...` - Problem: types for custom names not found anymore
Hint: the `swag fmt` reformats the comment, using a tab (\t) as a separator between `@name` and the type name.
After running `swag fmt`, the parser still finds all types.
I did rework the parser using some little regEx to use any kind of whitespace.
An additional test is provided as well.
----
Issue #1150 seems somewhat related, but I don't care what the `fmt` command does, rather the problem, the parser can't find custom types.
I did run `go run github.com/swaggo/swag/cmd/swag@latest fmt` yesterday, on a larger code base and afterward all custom …
=> fix using tab (\t) as separator for custom type names

parser.go, parser_test.go
Fixes #1267 
[e.g. https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1267)
=> fix required params parsing for routes with multiple paths and multiple params

operation.go, operation_test.go
Attempt to fix the issue #1608
https://github.com/swaggo/swag/issues/1608
Adding a test case with the commentLine expression similar to the one suggested in the issue.
=> fix: enums with `paramType`=body got parsed incorrectly

enums_test.go, package.go, testdata/enums/consts/const.go
=> parse binary literal const

parserv3.go, parserv3_test.go, testdata/v3/servers/main.go
Support for servers.variables.xxx
https://github.com/swaggo/swag/issues/1611
=> Feat servers variables of current spec

operation.go, parser.go, parser_test.go, testdata/global_security/api/api.go, testdata/global_security/expected.json, testdata/global_security/main.go
Add support global `@Security` tag. If need to disable security for an operation, an empty security tag is used.
#1453 
=> feat: global security

cmd/swag/main.go, gen/gen.go, gen/gen_test.go, generics_test.go, golist.go, golist_test.go, packages.go, parser.go, parser_test.go
Add cli flag --pdl to determine whether parse operations in dependency
```
swag init --pd            // for backward compatibility, only parse models indepedency
swag init --pdl 3        // 0 disabled, 1 only parse models, 2 only parse operations, 3 parse all
```
#1451
=> add cli flag --pdl to determine whether parse operations in dependency

cmd/swag/main.go, gen/gen.go, golist.go, parser.go, parser_test.go
This PR adds a `--packagePrefix=P` option for only parse packages matched by prefix P.
This is useful when our swagger annotations are located in dependency. In the meantime there are some 3rd-party dependency (that we have no control) has some malform swagger annotations, we can use this option to exactly parse the package we need.
Close https://github.com/swaggo/swag/issues/904
=> feat: add --packagePrefix=P for only parse packages matched by prefix P

format/format.go, format/format_test.go
Attempt to fix  #1635
#1635
Read the original file information and run a `chmod` to the new file.
Add a test case to validate file permission after format.
=> preserve file permission when writing formatted files

README_pt.md
Updates the curly braces for _PT ReadMe, as there's an extra start brac ```{``` for the param
This causes GitHub Pages using ```Jekyll``` to fail for applications that use this as a vendor package
```
Liquid Exception: Liquid syntax error (line 421): Variable '{{tipo de parâmetro}' was not properly terminated with regexp: /\}\}/ in Source/Server/vendor/[github.com/swaggo/swag/README_pt.md](http://github.com/swaggo/swag/README_pt.md)
```
=> docs(readme): fix param brace

format/format_test.go
`filepath.Join` already calls `filepath.Clean` on it's arguments. So, it's unnecessary to call `filepath.Clean` on the second argument.
=> test: remove redundant `filepath.Clean` call

operation.go
When the return value defined by the @Success tag is equal to the null value, make fixes to prevent a null pointer exception from occurring.
https://github.com/swaggo/swag/issues/1653
Since null could not be specified in swagger, an object was specified.
=> If @Success tag's return value equals null, prevent null pointer exceptions.

README.md, README_pt.md
Add Portuguese and English documentation about usage of the parser with Go generic types
#1655 
The examples were already being used as [test data](https://github.com/swaggo/swag/blob/master/testdata/generics_nested/api/api.go) but none added to the main README.md
=> docs: add PT and EN examples for Go generic types

operationv3.go, operationv3_test.go
This PR address the side effect on the operationv3, causes the parsed query with object type to consist of duplicated items.
=> fix: avoid shadowed variable on operationv3

parserv3.go, parserv3_test.go, testdata/v3/type_alias_definition/api/api.go, testdata/v3/type_alias_definition/expected.json, testdata/v3/type_alias_definition/main.go, testdata/v3/type_alias_definition/othertypes/types.go, testdata/v3/type_alias_definition/types/types.go
The fix for OpenAPI v3 definition parsing of go alias types 
https://github.com/swaggo/swag/issues/1590
-
=> fix: fixed definition parsing for alias types

Dockerfile, README.md
Currently the docker container has to be invoked with
```sh
docker run --rm -v $(pwd):/code -w /code ghcr.io/swaggo/swag:v1.16.2 /root/swag
```
which means users have to know that the binary is placed under `/root/swag`. If they don´t know this and just try
```sh
docker run --rm -v $(pwd):/code ghcr.io/swaggo/swag:v1.16.2
```
they will get the error
```sh
docker: Error response from daemon: No command specified.
```
if they then try
```sh
docker run --rm -v $(pwd):/code ghcr.io/swaggo/swag:v1.16.2 swag
```
it won´t work either
```sh
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "swago": executable file not found in $PATH
: unknown.
```
This PR adds …
=> Optimize docker container usage

README.md, cmd/swag/main.go, gen/gen.go, gen/gen_test.go, operation.go, parser.go, testdata/state/admin_expected.json, testdata/state/api/api.go, testdata/state/api/api_user.go, testdata/state/main.go, testdata/state/user_expected.json, testdata/state/web/handler.go
Add state flag
[e.g. https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1628)
In my project, my microservice implements a server for the user and the admin.
=> Add flag state #1628

operation.go
fix comments on some exported functions for lint check
=> fix comments on some exported functions for lint check

README.md, README_zh-CN.md, operation.go, operation_test.go, parser.go, testdata/deprecated_router/api/api.go, testdata/deprecated_router/expected.json, testdata/deprecated_router/main.go
add `@DeprecatedRouter` to deprecate some parts of routers in an operation
#1733 
```
@Router                      /a [GET]
@DeprecatedRouter   /a/b [GET]
```
=> deprecate some parts of routers in an operation

field_parser.go, field_parser_test.go
Change FormName. Trim bracket in filedname
In gin binding, an array parameter goes like
```go
type Teacher struct {
Books []string `form:"books[]"`
}
```
In swaggo/swag less than **v1.8.10**, it's field name should comes from ps.Filed.Names[0] which is "Names", which goes to toLowerCamelCase and generate "names".
```go
func (ps *tagBaseFieldParser) FieldName() (string, error) {
var name string
if ps.field.Tag != nil {
// json:"tag,hoge"
name = strings.TrimSpace(strings.Split(ps.tag.Get(jsonTag), ",")[0])
if name != "" {
return name, nil
}
}
if ps.field.Names == nil {
return "", nil
}
switch ps.p.PropNamingStrategy {
case SnakeCase:
return toSnakeCase(ps.field.Names[0].Name), …
```
=> :bug: array form filed name should not contains bracket which led to invalid fieldname in ts codegen

field_parser.go, operation.go, operation_test.go, parser.go, testdata/param_structs/structs.go
Supports "object" (i.e. struct model) data types for `header` and `path` parameter types via `@Param` operation comment in the same way that `query` and `formData` already work - basic structs are supported to represent multiple paramters at once.
This allows struct models, e.g. for a number of related headers, to be used directly rather than duplicating all the `@Param` comments for every field in those structs.
This works similarly to existing `formData` and `query` types and largely reuses all the same operation parsing logic.
In addition this supports using struct tags `header:"name"`  and `uri:"name"` for `header` and `path` params respectively. This follows the Gin specific tag naming conventions.
**Relation issues**
A few issues with similar feature requests:
- …
=> Struct fields supported for header and path param types

generics.go, generics_test.go, parser.go, testdata/generics_basic/api/api.go, testdata/generics_basic/expected.json, testdata/generics_names/expected.json, testdata/generics_nested/expected.json, testdata/generics_property/expected.json, types.go
Support generic with map params, especially, map and array can arbitrarily combine.
For example,
```
types.MyGeneric[map[string][][]string, []map[string][]string]
```
#1711
=> Feat: Support generic with map params

parser.go, parser_test.go
remove unneeded tags from general infos
#1759
=> fix: remove dropped tags from general infos

Dockerfile
While trying to use the binary from [ghcr.io/swaggo/swag:v1.16.3](https://github.com/swaggo/swag/pkgs/container/swag/173501427?tag=v1.16.3) I encountered an infinite error loop:
```
/usr/local/go/src/internal/syscall/unix/at_wasip1.go:12:2: UTIME_OMIT redeclared in this block
/usr/local/go/src/internal/syscall/unix/at_sysnum_linux.go:18:2:        other declaration of UTIME_OMIT
/usr/local/go/src/time/zoneinfo_wasip1.go:8:5: platformZoneSources redeclared in this block
/usr/local/go/src/time/zoneinfo_unix.go:21:5:   other declaration of platformZoneSources
/usr/local/go/src/time/zoneinfo_wasip1.go:10:6: initLocal redeclared in this block
/usr/local/go/src/time/zoneinfo_unix.go:28:6:   other declaration of initLocal
/usr/local/go/src/internal/poll/fd_wasip1.go:13:6: SysFile redeclared in …
```
=> Update docker go build version to 1.21

field_parser.go, field_parser_test.go, operation.go
Added support for "title" property, as defined by [Openapi Specification Schema Object](https://swagger.io/specification/v2/).
The property is provided via "title" tag on structs.
none
The problem arose from having to generate the API in typescript for the client through openapi-generator. Because some fields (marked with "x-nullable") were considered "Inline Models" and the openapi-generator CLI suggested using the "title" field to give it a unique name, i tried to find a ready-made solution with no luck.
The "schema" struct already contained the "Title" field, but this is never assigned, so I proceeded to complete the assignment of the field through the "title" tag.
**Usage:**
the following definition:
```
type …
```
=> feat: Add support for "title" property

README.md, cmd/swag/main.go
=> chore: fix some typos in comments

.github/workflows/ci.yml, Makefile, README.md, README_pt.md, README_zh-CN.md
=> bump go version

packages.go
In some situations, such as when using the go-swag Nix package, `runtime.GOROOT()` will be empty, and `RangeFiles` will skip all source paths since technically, all paths are prefixed with the empty string.
See also https://github.com/NixOS/nixpkgs/issues/224701
May resolve some cases of https://github.com/swaggo/swag/issues/1622.
https://github.com/NixOS/nixpkgs/issues/224701
https://github.com/swaggo/swag/issues/1622
=> Handle case of empty GOROOT

.github/workflows/docker.yml, Dockerfile
Fix https://github.com/swaggo/swag/issues/1755 by enabling go cross-compilation in Dockerfile and setting multiple target architectures in docker/build-push-action.
https://github.com/swaggo/swag/issues/1755 - Create multi-arch docker image for amd64/arm64 
Validated the Dockerfile change by building a multi-arch image locally. ~~I have no way to test the change in github worklfow though.~~ Thanks to @ngehrsitz, changes to github workflow could be validated on this fork repo, too.
=> Feat: multi-arch docker image

packages.go
the path filter will filter out the code path in this scenario: the $GOROOT path is "~/development/go" and the code path is "~/development/golang/src/github.com/xxxx"
https://github.com/swaggo/swag/issues/1780
the limitation may need to be written into documentation.
=> fix issue: #1780: filter $GOROOT path

testdata/simple/api/api.go, testdata/simple/expected.json
PR https://github.com/swaggo/swag/pull/1813 introduced test changes to both testdata/simple/expected.json and testdata/simple/api/api.go which were misaligned and out of alphabetical order. This is now fixed.
See comment and test errors after https://github.com/swaggo/swag/pull/1813
=> [Issue 1812] fix misalignment in expected.json and api.go, fixing test

parser.go
Fixes the issue described in https://github.com/swaggo/swag/issues/1829
https://github.com/swaggo/swag/issues/1829
The previous logic could select the wrong markdown file if one tag was a substring of another. E.g. "objects" and "my-special-objects".
=> Fixes Issue 1829

operation.go, operation_test.go
Closes #1834
When overriding with `any` or `interface{}`, the code should prefer the "any" (empty) schema instead, not the object schema since that's different e.g.
```
replace json.RawMessage any
```
```go
type Thing struct {
data json.RawMessage `json:"data"`
}
```
```json
"model.Thing": {
"type": "object",
"properties": {
"data": {}
}
}
```
`make all`
=> Fix global overrides for any/interface ref types

packages.go, parser_test.go, testdata/simple/api/api.go, testdata/simple/expected.json
In https://github.com/swaggo/swag/pull/1813 I introduced additional support to complex fields in function-scoped types.
We have since then found a missing case: When a field is a pointer to a function-scoped type it does not get picked up properly.
=> adds support for pointer function scoped fields

generics.go, packages.go, parser.go, parser_test.go, testdata/alias_nested/cmd/main/main.go, testdata/alias_nested/expected.json, testdata/alias_nested/pkg/bad/data.go, testdata/alias_nested/pkg/good/data.go, types.go
Using aliases only for describing definitions
#1863 
A field has been added to TypeSpecDef, which defines the name of the result definition (SchemaName)
=> [issue 1863] fix parse nested structs and aliases

generics_test.go, packages.go, testdata/generics_function_scoped/api/api.go, testdata/generics_function_scoped/expected.json, testdata/generics_function_scoped/main.go, testdata/generics_function_scoped/types/response.go
In https://github.com/swaggo/swag/pull/1866 PR, the `SchemaName` field added to `TypeSpecDef` struct is not set for function scoped types. This PR sets `TypeSpecDef.SchemaName` for function scoped types too.
Also added some tests for the cases this PR fixes.
fixes #1882
=> Fix generics used with function scoped types

operation.go, operation_test.go
This PR fixes a param comment issue where a `\n` gets escaped into `\\n` so it would not be applied to the output swagger file.
I believe this should be the right behavior.
Thank you!
=> Fixed a param comment escaping issue where newline characters do not get applied in the output swagger file

packages.go, parser.go
support markdown description for declaration
usage:
```go
// MyStruct ...
// @description.markdown my-struct.md
type MyStruct struct{
....
}
```
this pr will read markdown file content as declaration description
fix: range PackagesDefinitions.uniqueDefinitions cause panic
=> support markdown description for declaration

README.md, parser.go, parserv3.go, parserv3_test.go, schema.go, testdata/v3/main.go
add `securitydefinitions.bearerauth` for [bearer-authentication documentation](https://swagger.io/docs/specification/authentication/bearer-authentication/)
https://github.com/swaggo/swag/issues/1853
=> feat: add securitydefinitions.bearerauth for bearer token setting in V2

README.md
the feature request header or custom request header in swaggo is already implemented by pr #30. However, it has not yet been documented.
And this is the reason for the pr
https://github.com/swaggo/swag/issues/29
Just a simple documentation extension
=> Update docs for request and response headers

field_parser.go, field_parser_test.go, parser.go
parse all fields names declared in a row
#1871
=> fix：parse all field names declared in a row

README.md
**Remove cannot find type definition error**
```go
package model
type PaginatedListResp[T any] struct {
Data         []T  `json:"data"`
TotalCount   int  `json:"total_count"`
HasMore      bool `json:"has_more"`
Page         int  `json:"page"`
ItemsPerPage int  `json:"items_per_page"`
}
type User struct {
ID          uuid.UUID `json:"id"`
Name        string    `json:"name"`
PhoneNum    string    `json:"phone_number"`
Email       string    `json:"email"`
Username    string    `json:"username"`
}
```
```go
package api
.
.
.
//	@Success	200	{object}	models.PaginatedListResp[models.User]
```
If the model is part of an external dependency or internal package then flags mentioned in the PR can be used but were not mentioned in the generics section.
In some cases simple …
=> Flags to parse internal and dependency package

enums_test.go
This PR makes `enums_test.go` pass on 32-bit architectures.
#1633
=> fix: failing assert in enums test on 32bit

operation.go, operation_test.go
Allow route patterns with parenthesis i.e. `/odata/Resource({id}) [get]`
[e.g. https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1799)
Odata specification allows for single resource lookups using the described syntax, but it currently generates a `cannot parse router comment` error. This just adds parenthesis to the regex to fix the error.
=> Feat: Add support for parenthesis in router patterns

README.md, parser.go, parser_test.go
I'm using [ReDoc](https://redocly.github.io/redoc/) to generate own documentation from OpenAPI specification. They have `x-displayName` parameter for tags.
Example:  [museum.yaml](https://redocly.github.io/redoc/museum.yaml)
```yaml
tags:
- name: Operations
x-displayName: About the museum
description: Operational information about the museum.
```
https://github.com/swaggo/swag/issues/1784
=> Added support for @tag.x- attributes for tags (#1784)

enums.go, parser.go, testdata/enums/expected.json
This pull request introduces the `x-enum-descriptions` extension to the generated Swagger documentation when working with enums. The new extension provides a list of descriptions for enum values, aligned with the x-enum-varnames.
A new constant enumDescriptionsExtension has been added to support the x-enum-descriptions extension.
The ParseDefinition function has been updated to create a x-enum-descriptions list based on the order of x-enum-varnames and corresponding enum comments.
The `x-enum-comments` and `x-enum-varnames` are now matched in order, and their descriptions are output in the `x-enum-descriptionfs` array.
Test cases have been updated to reflect the addition of x-enum-descriptions, demonstrating the new output in the expected JSON.
The addition of x-enum-descriptions enhances …
=> feat: Add x-enum-descriptions to generated Swagger documentation for Enum

field_parser_v3_test.go, field_parserv3.go, operation.go, operationv3.go, parserv3.go, parserv3_test.go, testdata/v3/simple/api/api.go, testdata/v3/simple/web/handler.go
Adds support for the oneOf feature in OpenAPI v3, allowing you to describe a field/response that can have multiple types.
https://github.com/swaggo/swag/issues/1363
https://github.com/swaggo/swag/issues/1617
Unfortunately, the PR https://github.com/swaggo/swag/pull/1671 was reverted due to a compile error caused by the use of the `maps` package. 
The `maps` package was introduced in Go 1.21, but the project is currently using Go 1.18.
=> Feat openapiv3 oneof

operation.go, parser.go
When a comment has an error then we print only a file name and the error text but not the comment that caused an error. To make it easier to understand print it.
**Context:**
I spent a lot of time while investigating the error message:
Generating dto.DeleteRequest
Key is not supported paramType
It turned out that the DTO was fine but a problem was in another place with a comment:
// @Param User Key body dto.UserRequest true "Event"
In the comment instead of `UserKey` it was written `User Key` and the Key was threatened as a `paramType`. I wasn't able to figure out which key they are talking about.
So the change should significantly improve troubleshooting which is important.
=> feat: ParseComment error to contain the comment

parser.go, parser_test.go
=> support generate var-declared function doc

cmd/swag/main.go
Remove duplicate `templateDelimsFlag` added by merge https://github.com/swaggo/swag/commit/2fa63cf53d70201b19a0ac77b0bdcf564dfefc6e
=> fix: fix merge error caused by 2fa63cf

README.md, operationv3.go, operationv3_test.go
Adding the `@servers` param to the operation level.
None
Based on this: https://swagger.io/docs/specification/v3_0/api-host-and-base-path#overriding-servers
=> Add support for servers on operation level for 3.1

formatter.go, formatter_test.go, go.mod, go.sum
This PR formats the command outputs using goimports.
goimports is a popular tool among Go users for formatting code. The code generated by swag can sometimes conflict with the formatting expected by goimports. This PR addresses that problem by ensuring the swag-generated code is formatted using goimports.
Fix https://github.com/swaggo/swag/issues/1929
=> Fix format by goimports

parser.go, types.go
Since this PR https://github.com/swaggo/swag/pull/1866 was merged, the tag `@name` doesn't work anymore for recursion, as you can see on this issue: https://github.com/swaggo/swag/issues/1909.
This PR is to use the new field schemaName in case of recursion
https://github.com/swaggo/swag/issues/1909
=> fix: @name for recursion

README.md
- The link in the README file does not direct users to the correct section when clicked. Although the target section exists, it is incorrectly titled as "Add response request", which causes the link to fail. This issue disrupts navigation within the documentation.
- This Pull Request resolves the issue by:
1. Updating the section title in the README from "Add response request" to "Add Request Headers" to align with the 
hyperlink.
2. Alternatively, modifying the hyperlink to match the existing section title if renaming the section is not suitable.
- The fix is a small but meaningful improvement to the overall documentation quality.
=> Fix typo error in README

field_parser_v3_test.go, field_parserv3.go
some enums was not being generate when setting flag `--v3.1=true` 
e.g it was like this:
```
"SomeEnum": {,
"type": "string",
"x-enum-varnames": [
"SomeEnumA",
"SomeEnumB"
]
}
```
with this PR is like this:
```
"SomeEnum": {
"enum": [
"confirmation_code",
"transaction_confirmation"
],
"type": "string",
"x-enum-comments": {
"SomeEnumA": "a",
"SomeEnumB": "b"
},
"x-enum-varnames": [
"SomeEnumA",
"SomeEnumB"
]
}
```
https://github.com/swaggo/swag/issues/1955
=> fix: enum generation in v3.1

README.md, README_pt.md, README_zh-CN.md, operation.go, parser_test.go
When working with this library I found that it was failing when I was trying to document my SSE endpoint, and apparently, it was due to a missing MIME Type in the library. 
Let me know if I need to change the target branch to V2 or if I'm missing anything!
https://github.com/swaggo/swag/issues/1931
=> chore: accept event streaming

golist.go
The current implementation of getting a list of packages (`listPackages`) assumes that a non-empty stderr in the output of `go list` is an error, regardless of the result of the call, which is not true. Here is an example of a non-empty stderr:
```
go: downloading github.com/go-sql-driver/mysql v1.8.1
go: downloading github.com/go-errors/errors v1.0.1
go: downloading github.com/go-playground/validator/v10 v10.22.1
...
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.53.0
go: downloading github.com/felixge/httpsnoop v1.0.4
```
There is no information on errors. This is [a legitimate output of additional information](https://github.com/golang/go/blob/e33f7c4/src/cmd/go/internal/modfetch/fetch.go#L231).
As a result, we get a non-zero status …
=> Non-empty stderr for `go list` is not an error in itself

field_parserv3.go
This PR fixes a potential panic.
=> fix: avoid panic in ComplementSchema due to nil schema references

cmd/swag/main.go, parserv3.go
The @name tag does not work for init with the --v3.1 flag.
This PR introduces the use of the new schemaName field in the case of ParseDefinitionV3.
Additionally, it fixes a Segmentation Fault that occurred during startup due to a duplicate flag.
https://github.com/swaggo/swag/issues/1909
=> fix: @name does not working for v3.1

parserv3.go
Fixes parsing of security definitions on V2
https://github.com/swaggo/swag/issues/1941
=> fix: getSecurityDefinitionKey white space parsing

cmd/swag/main.go
`(default: false)` is already generated automatically:
```bash
--parseFuncBody                            Parse API info within body of functions in go files, disabled by default (default: false) (default: false)
```
=> Remove redundant `(default: false)` for parseFuncBody flag

cmd/swag/main.go
Fix duplicate version printing when running swag -v.
N/A
Previously, running swag -v printed the version multiple times. This PR ensures that the version is displayed only once.
=> [v2] fix: duplicate print version

README.md, field_parser.go, field_parser_test.go
- Enhances field parser to recognize 'omitempty' in `json:` tag as `required: false`, updating IsRequired logic (following existing pattern present in parsing logic) and adding corresponding test case. 
- Update README to document the new behavior w.r.t `json:omitempty`
Related: #2040  
While I believe this behavior makes the most sense to use in conjunction with the `--requiredByDefault` flag - there is no hard requirement or dependency to force both these options to co-exist.  Implementation gives preference to existing supported `tag` values ( `binding` + `validate`) so anything presently relying on them for `required` calculation is unaffected by this change.
=> feat: json:omitempty marks field as optional

cmd/swag/main.go, gen/gen.go, parser.go
I have added an extra flag that removes long names from struct definitions when using the `--pd` flag. 
Example:
Struct is in `myProject/internal/database/model/mytest.go`
Struct's name is `MyTest`
Outcome without the schema rename of `myProject_internal_database_model.MyTest`. 
``` json
"definitions": {
"myProject_internal_database_model.MyTest": {
"type": "object",
"properties": {
"data": {
"type": "string"
}
}
}
}
```
Outcome with the schema rename `MyTest`. 
``` json
"definitions": {
"MyTest": {
"type": "object",
"properties": {
"data": {
"type": "string"
}
}
}
}
```
This makes generating code from the swagger JSON way more readable. 
Add any other context about the problem …
=> Use the structs name without the @name comment

version.go
related: #2042
Per request from community - updating version.go to v1.16.7 to ensure that the version command of the client properly reports the version for the next release.
=> chore: update version.go to v1.16.7

parserv3_test.go, schemav3.go, testdata/v3/interface/api/api.go, testdata/v3/interface/expected.json, testdata/v3/interface/main.go, testdata/v3/interface/types/types.go
This fixes the panic when using interface-valued schemas (the added test was panicking before fix).
Seems to be a regression from #1985.
=> Fix for interface-valued schemas
